### PR TITLE
Fix login failure handling during hydration

### LINKED ISSUE #7397: Wrong login credentials not showing errors on 401 error
**Describe the bug**
When trying to login with wrong credentials, and backend responds with 401 - unauthorized, no errors are shown and loader on submit login doesn't disappear. 

**To Reproduce**

1. Go to '/login.'
2. Insert wrong credentials
3. Press login button
4. See error: loader is still loading and no error are displayed

**Expected behavior**
Display error and remove laoder on submit button. 

**Software (please complete the following information):**

- OS: MAc
- Browser: Chrom
- Volto Version [e.g. 18.25.0]
- Plone Version [e.g. 6.1.0]
- Plone REST API Version [e.g. 9.1.0]

**Additional context**
I think the problem is in middleware/api.js when handling error (line ~310).
In that moment, isHydrating is true, because it becomes false only when you have a positive response, and `hasExistingError` consider only `content` action, but here we are in a static view (/login) not related to any content,  so it returns and not handles errors. 

Another problem i think there's in this error handling, is that `config.settings.actions_raising_api_errors` doesn't contains action `LOGIN`

@sneridagh the error was introduced here 
https://github.com/plone/volto/pull/7192/files#diff-01d7617436701d779414389f02f43b75a948e31334e862f240ff8c3b6f45e82b

### PR DESCRIPTION
**Pull request by aryan7081**
Fixes #7397
Backport Ref #7625 
When login fails with a 401 Unauthorised error, the loader keeps spinning. This is because the hydration guard in `middleware/api.js` short-circuited every action (including `LOGIN_FAIL`) while `isHydrating` was true, so the error handler returned early before dispatching `LOGIN_FAIL`.

This patch limits the hydration guard to `GET_CONTENT` only, so user-initiated actions like `LOGIN` always dispatch their `_FAIL` actions and stop the loader. It also adds `LOGIN` to `settings.actions_raising_api_errors`, ensuring the global API error handler surfaces 401s properly.

### CODE REVIEW

File: packages/volto/src/middleware/api.js [hunk 1]
```diff
@@ -341,8 +341,13 @@ const apiMiddlewareFactory =
         (error) => {
           // Make sure an error during hydration
           // (for example when serving an archived page)
-          // doesn't hide the SSR content.
-          if (isHydrating && !hasExistingError) {
+          // doesn't hide the SSR content. Only suppress GET_CONTENT failures;
+          // user-initiated actions (LOGIN, etc.) must always dispatch _FAIL so
+          // loaders stop and errors surface.
+          const shouldIgnoreHydrationError =
+            isHydrating && !hasExistingError && type === GET_CONTENT;
```
Comment (wesleybl) [inline packages/volto/src/middleware/api.js:348]: Perhaps it's best to be more conservative here and use `type !== LOGIN`.

Do you see any other situations where not having `type === GET_CONTENT` might be detrimental?

File: packages/volto/src/config/index.js [hunk 2]
```diff
@@ -98,7 +98,7 @@ let config = {
     proxyRewriteTarget: process.env.RAZZLE_PROXY_REWRITE_TARGET || undefined,
     // apiPath: process.env.RAZZLE_API_PATH || 'http://localhost:8000', // for Volto reference
     // apiPath: process.env.RAZZLE_API_PATH || 'http://localhost:8081/db/web', // for guillotina
-    actions_raising_api_errors: ['GET_CONTENT', 'UPDATE_CONTENT'],
+    actions_raising_api_errors: ['GET_CONTENT', 'UPDATE_CONTENT', 'LOGIN'],
```
Comment (wesleybl) [inline packages/volto/src/config/index.js]: This is not necessary. The login does not have a specific error screen.

**Comment by aryan7081** [comment]
@wesleybl Thanks for the review! I have addressed both the comments. The build failure is unrelated to my changes. It's a TypeScript error in `@plone/components` package's `ColorPicker.tsx` where the `ColorPickerProps` interface has a type mismatch with `react-aria-components` `ColorPickerProps` regarding the `children` property.
Thanks!

File: packages/volto/src/middleware/api.js (hunk 1 above)
Comment (wesleybl) [reply packages/volto/src/middleware/api.js:348]: I'm not sure if my suggestion is the most correct one.

@davisagli  you added this check in #7148 to make the archived Volto site accessible: #7132

But this caused this side effect. My suggestion is more conservative, but other errors of this type may occur.

Opinion?

File: packages/volto/news/7397.bugfix [hunk 3]
```diff
@@ -0,0 +1 @@
+Prevent login failures during hydration from being swallowed by GET_CONTENT-only guard and treat LOGIN as an action that should surface API errors. @aryan7081
```
Comment (wesleybl) [inline packages/volto/news/7397.bugfix]: Remove: `and treat LOGIN as an action that should surface API errors`

File: packages/volto/news/7397.internal [hunk 4]
```diff
@@ -0,0 +1 @@
+Add Cypress regression test ensuring login failures stop the loader and show the toast notification. @aryan7081
```
Comment (wesleybl) [inline packages/volto/news/7397.internal]: It is not necessary to add a note for tests, unless only the test was added.

File: packages/volto/src/middleware/api.js (hunk 1 above)
Comment (davisagli) [reply packages/volto/src/middleware/api.js:348]: In general isHydrating is marked as false as soon as any API call processed by this middleware succeeds. So we only get this type of problem when the first API has an error that we actually do want to report to the user.

As is, the PR should be enough to fix the specific error with the login form that we know about and understand, so I'll approve it.

It might be possible to do a better fix by being more selective about which errors we ignore here (mostly we want to avoid destorying the SSR content if there's a connection error because there's no actual backend available...but if we called the backend and got a response that is has an error status, it's ok to process the error normally).

File: packages/volto/news/7397.bugfix (hunk 3 above)
Comment (davisagli) [reply packages/volto/news/7397.bugfix]: Let's write a release that focuses on the impact on the user rather than the technical details of the fix (someone who cares about the details can follow the link to the PR):

```suggestion
Fixed a bug in the login form where the user could see a spinner instead of an error message after a failed login, when the login form was loaded via server-side rendering. @aryan7081
```

File: packages/volto/news/7397.internal (hunk 4 above)
Comment (davisagli) [reply packages/volto/news/7397.internal]: I agree, the test is part of the overall fix. Please just remove this file.

Comment (aryan7081) [reply packages/volto/news/7397.internal]: I have removed this file.
Thanks for the clarification!

File: packages/volto/src/middleware/api.js (hunk 1 above)
Comment (wesleybl) [reply packages/volto/src/middleware/api.js:348]: @davisagli This error might be more common than we think. It likely occurs in the password reset form. And it can occur in any custom form. It's difficult to debug. So now that we're looking at this more closely, can we find a smarter solution?

If I understand correctly, what makes the content "disappear" is the global error page, which says the backend is down. So, is it safe to test only `GET_CONTENT`? Other errors won't display this global error page.

Comment (davisagli) [reply packages/volto/src/middleware/api.js:348]: @wesleybl @aryan7081 I tested this some more, and yes, I think we can change this back to `&& type === GET_CONTENT`

Comment (aryan7081) [reply packages/volto/src/middleware/api.js:348]: @wesleybl @davisagli I have restored hydration error check to `GET_CONTENT` only. Please review.
Thanks!

File: packages/volto/cypress/tests/core/basic/login.js [hunk 5]
```diff
@@ -14,4 +14,16 @@ describe('Login Tests', () => {
     cy.get('#login-form-submit').click();
     cy.get('body').should('have.class', 'has-toolbar');
   });
+
+  it('Shows an error when logging in with wrong credentials', function () {
```
Comment (wesleybl) [inline packages/volto/cypress/tests/core/basic/login.js:18]: This error only occurs in SSR. You need to reload the `/login` page.

Comment (davisagli) [reply packages/volto/cypress/tests/core/basic/login.js:18]: Adding `cy.reload();` here should do it.
```suggestion
  it('Shows an error when logging in with wrong credentials', function () {
    cy.reload();
```

**Comment by wesleybl** [comment]
@aryan7081 @davisagli Thank you for addressing this complicated problem!

**Comment by wesleybl** [comment]
@aryan7081 Could you please do a backport to Volto 18?
