### PR TITLE
hamburger icon fixed

### LINKED ISSUE #5353: Hamburger Icon in small screen is not working
**Describe the bug**
Hamburger icon is not containing any data and it is useless to keep this in the navbar.

**To Reproduce**
we can remove this icon or make it disable, we can also give some list that will render when we click on icon.

1. Go to 'Homeapage'
2. Click on 'Inspect and make screen samll'
3. Scroll down to 'then you will see the hamburger icon and click on it'

**Expected behavior**
It should not be there or should not show blank page on clicking on it.

**Screenshots**
image
image

**Software (please complete the following information):**

- OS: Windows
- Browser:  Chrome
- Volto VersionL: 17.1.1
- Plone Version : 6.0.6
- Plone REST API Version:  8.40.0

### PR DESCRIPTION
**Pull request by Aarav238**
Fixes #5353

### CODE REVIEW

**Comment by ichim-david** [comment]
@Aarav238 you are making assumptions about the title being home which is incorrect.
Read again the suggestion added in the issue https://github.com/plone/volto/issues/5353#issuecomment-1788424026

**Comment by Aarav238** [comment]
Thanks @ichim-david for reviewing , Now i have added the state that is checking if the navigation items are empty or undefined. 
On the basis of that hamburger will be rendered.

**Comment by stevepiercy** [comment]
@Aarav238 you must not break any tests, and all tests must pass. No one will review your pull request until it passes all tests and code quality checks. Please see [Code quality](https://6.docs.plone.org/volto/contributing/index.html#code-quality).

**Comment by Aarav238** [comment]
@stevepiercy Can you please help me in this ? How I can pass all the test?

**Comment by stevepiercy** [comment]
@Aarav238 please see [Code quality](https://6.docs.plone.org/volto/contributing/index.html#code-quality). If something is not clear in the documentation, please create a new issue for that. Volto's documentation for newcomers might not be clear in some places, and newcomers like you can point out what is missing.

**Comment by Aarav238** [comment]
Hey @stevepiercy , Now all the tests are passed. Please  review this PR.

File: packages/volto/src/components/theme/Navigation/Navigation.jsx [hunk 1]
```diff
@@ -48,40 +59,42 @@ const Navigation = (props) => {
...
-          }
-          type="button"
-          onClick={toggleMobileMenu}
-        >
-          <span className="hamburger-box">
-            <span className="hamburger-inner" />
-          </span>
-        </button>
-      </div>
+      {showHamburger ? (
```
Comment (davisagli) [inline packages/volto/src/components/theme/Navigation/Navigation.jsx:64]: This can be done more simply. Just do this here:
```suggestion
      {items?.length ? (
```
and then you don't need to add a new variable to the component state above.

**Review by davisagli — CHANGES_REQUESTED** [review]

**Comment by Aarav238** [comment]
@davisagli  Thanks for the suggestion, I have removed the state variable.

File: packages/volto/src/components/theme/Navigation/Navigation.jsx [hunk 2]
```diff
@@ -26,7 +26,7 @@ const Navigation = (props) => {
   const intl = useIntl();
   const dispatch = useDispatch();
   const { pathname, type } = props;
-  const [isMobileMenuOpen, setisMobileMenuOpen] = useState(false);
+  const [isMobileMenuOpen, setisMobileMenuOpen] = useState(null);
```
Comment (davisagli) [inline packages/volto/src/components/theme/Navigation/Navigation.jsx:29]: Please change the default value of isMobileMenuOpen back to false; this change isn't needed.

**Review by davisagli — CHANGES_REQUESTED** [review]
I tested it and it works well. Just one more small request, please.

**Comment by Aarav238** [comment]
Done @davisagli , I have changed the default value to false.

File: packages/volto/news/5353.bugfix [hunk 3]
```diff
@@ -0,0 +1 @@
+Fixed hamburger icon visibility in mobile/tablet view. @Aarav238
```
Comment (davisagli) [inline packages/volto/news/5353.bugfix:1]:
```suggestion
The hamburger icon to open the mobile/tablet navigation is now hidden if there are no navigation items. @Aarav238
```

**Review by davisagli — APPROVED** [review]
@Aarav238 Thanks for your contribution!

**Comment by Aarav238** [comment]
Thanks @davisagli !
