### PR TITLE
Fixing file-preview other than image

### LINKED ISSUE #1752: Preview image in file upload widget is broken when uploading a file
Steps to reproduce:

- Go to Volto root, create a new File
- Choose a file in the input type="file"  widget

Screenshot_20200821_141023

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes #1752

### CODE REVIEW

File: src/components/manage/Widgets/FileWidget.jsx [hunk 1]
```diff
@@ -11,6 +11,8 @@ import { readAsDataURL } from 'promise-file-reader';
 import deleteSVG from '@plone/volto/icons/delete.svg';
 import { Icon, FormFieldWrapper } from '@plone/volto/components';
 
+const fileExtension = ['image/png', 'image/jpeg', 'image/webp', 'image/jpg'];
```
Comment (tisto) [inline src/components/manage/Widgets/FileWidget.jsx:14]: @iFlameing what about gif?

Comment (tiberiuichim) [reply src/components/manage/Widgets/FileWidget.jsx:14]: Better name, `imageMimetypes` ?

**Review by tiberiuichim — CHANGES_REQUESTED** [review]

File: src/components/manage/Widgets/FileWidget.jsx (hunk 1 above)
Comment (iFlameing) [reply src/components/manage/Widgets/FileWidget.jsx:14]: yeah!!

**Review by tisto — APPROVED** [review]
