### PR TITLE
Include a File content view. refs #6707

### LINKED ISSUE #6707: [Seven Content Area Views] - File
> [!IMPORTANT]
> If you are not a member of the Volto Team or Developers Team in the Plone GitHub organization, then do not work on or comment on this issue.

The File content type view.

**Link to the parent PLIP**

https://github.com/plone/volto/issues/6638

### PR DESCRIPTION
**Pull request by frapell**
> [!CAUTION]
The Volto Team has suspended its review of new pull requests from first-time contributors until the [release of Plone 7](https://plone.org/download/release-schedule), which is preliminarily scheduled for the second quarter of 2026.
> [Read details](https://6.docs.plone.org/volto/contributing/index.html).

-----

- [X] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [X] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [X] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [X] I successfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [X] I successfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [ ] I successfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [X] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [X] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

Closes #6707

-----

If your pull request includes changes to the documentation—either in narrative documentation, Storybook, or configuration—then a pull request preview will be generated and a link will populate in the description of your pull request below.
By clicking that link, you can use the visual diff menu in the upper right corner to navigate to pages that have changes, then display the diff by checking the `Show diff` checkbox.

### CODE REVIEW

File: packages/layout/views/FileView.tsx [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+      <h1 className="documentFirstHeading">{content.title}</h1>
+      {content.description && (
+        <p className="documentDescription">{content.description}</p>
+      )}
+      {content.file?.download && (
+        <a href={flattenToAppURL(content.file.download)}>
+          {content.file.filename
+            ? content.file.filename
+            : t('layout.FileView.download')}
+        </a>
```
Comment (pnicolli) [inline packages/layout/views/FileView.tsx]: I recommend using the Link component from `@plone/components`  that takes care of client side rendering giving us a little perf boost. I would add the download attribute with the file name while you're there, as we did in the Image View: https://github.com/plone/volto/pull/7513

Final note, I forgot to tell everybody at the introduction, we are not using flattenToAppURL anymore. TLDR: we don't need that in Seven. The long story is that we are basically doing that for everything that we receive from the backend upfront, in the function that fetches the data.

**Review by pnicolli — CHANGES_REQUESTED** [review]

File: packages/layout/views/FileView.tsx (hunk 1 above)
Comment (frapell) [reply packages/layout/views/FileView.tsx]: @pnicolli Done :)

**Review by pnicolli — APPROVED** [review]

File: packages/layout/views/FileView.tsx [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+  }
+
+  const { content } = rootData;
+
+  return (
+    <Container className="view-wrapper">
+      <h1 className="documentFirstHeading">{content.title}</h1>
+      {content.description && (
+        <p className="documentDescription">{content.description}</p>
+      )}
```
Comment (davisagli) [inline packages/layout/views/FileView.tsx:21]: @sneridagh @pnicolli Should we try to be consistent about using a slot for the title & description in non-block-based views?
