### PR TITLE
Try to sort out volto's use of language codes

### LINKED ISSUE #4644: Using Volto in Brazilian Portuguese crash when access "Page not found 404"
**Describe the bug**

Error when accessing a non-existent URL in the browser, when the language code is **pt-br**, the "404 Not Found page" is not displayed and crash frontend.

When select  language code **en**, the "404 Not Found page" is displayed.

**To Reproduce**

1. Create a Volto project:

```
cookiecutter gh:collective/cookiecutter-plone-starter

project_title [Project Title]: 
project_slug [project-title]: 
description [A new project using Plone 6.]: 
author [Plone Foundation]: 
email [collective@plone.org]: 
python_package_name [project_title]: 
plone_version [6.0.3]: 
volto_version [16.18.0]: 
volto_generator_version [6.3.0]: 
Select language_code:
1 - en
2 - de
3 - es
4 - pt-br
Choose from 1, 2, 3, 4 [1]: 4
github_organization [collective]:
...
```

2. Start backend and volto.

```
Proxying API requests from http://localhost:3000/++api++ to http://localhost:8080/Plone
🎭 Volto started at 0.0.0.0:3000 🚀
[React Intl] Missing message: "skiplink-main-content" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "skiplink-navigation" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "skiplink-footer" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Site" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Plone Site" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Plone Site" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Open menu" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Open menu" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Search" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Search Site" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Search" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Search" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Breadcrumbs" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Home" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Copyright" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "The {plonecms} is {copyright} 2000-{current_year} by the {plonefoundation} and friends." for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Plone{reg} Open Source CMS/WCM" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Plone Foundation" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Distributed under the {license}." for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "GNU GPL license" for locale: "pt-BR", using default message as fallback.
[React Intl] Missing message: "Powered by Plone & Python" for locale: "pt-BR", using default message as fallback.
```

3. Access for example http://localhost:3000/abc in the browser 
```
RangeError: Incorrect locale information provided
    at Function.supportedLocalesOf (<anonymous>)
    at /home/user/project-title/frontend/node_modules/intl-locales-supported/src/index.ts:45:23
    at Array.every (<anonymous>)
    at Object.areIntlLocalesSupported [as default] (/home/user/project-title/frontend/node_modules/intl-locales-supported/src/index.ts:43:27)
    at createIntl (/home/user/project-title/frontend/node_modules/react-intl/dist/components/provider.js:65:42)
    at new IntlProvider (/home/user/project-title/frontend/node_modules/react-intl/dist/components/provider.js:88:19)
    at processChild (/home/user/project-title/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3305:14)
    at resolve (/home/user/project-title/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/user/project-title/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/user/project-title/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
sswp> !!! Script exited with code 1
```

**Expected behavior**
I hope the "display a 404 Not Found page" is displayed.

**Software (please complete the following information):**

- OS: Ubuntu 22.04
- Browser chrome
- Volto Version 16.18.0
- Plone Version 6.0.3
- Plone REST API Version 8.35.3

### PR DESCRIPTION
**Pull request by davisagli**
This aims to fix how volto handles language codes when there is a suffix for the region/country (e.g. `pt-br`/`pt_BR`/`pt-BR`).

Unfortunately volto needs to deal with 3 different formats:
- `pt-br`: This is stored in the Plone backend, and documented as the format expected in volto config.
- `pt-BR`: This format is expected by react-intl. After this PR, it also becomes the standard format used in the volto Redux store
- `pt_BR`: This format is expected by gettext and used in .po filenames. Also used in the I18N_LANGUAGE cookie.

So I've created helper functions to convert to each of these formats, and have tried to use them consistently everywhere:
- `toBackendLang`: converts to `pt-br`
- `toReactIntlLang`: converts to `pt-BR` (new name for `toLangUnderscoreRegion`)
- `toGettextLang`: converts to `pt_BR` (new name for `normalizeLanguageName`)

The old function names are kept for backward-compatibility; this aims to be safe to backport for volto 16.

I've done some manual testing, but this still needs to be checked in a multilingual site to make sure I didn't break the translation views.

Fixes #4644. It may help with #3786 as well, but I see 2 requests for /@actions even in an English site, so I'm not sure that one is related to language codes.

### CODE REVIEW

**Comment by wesleybl** [comment]
@davisagli I can confirm that duplicate requests no longer occur when we configure Volto with `pt-br`. Well actually the `@actions` request still happens twice. But before this PR, when pressing F5, it occurred 3 times. So we have a breakthrough.

Using `en` or `pt-br` the request `@actions` occurs twice, but navigating normally by links (without F5). But what we're looking at here is #2781

I can also confirm that the "not found" page is displayed normally with `pt-br`.

Thanks for fixing this!

**Review by wesleybl — CHANGES_REQUESTED** [review]
I tested a multilingual site, and the URL stay `http://localhost:3000/pt-BR` when it should be `http://localhost:3000/pt-br`

**Review by sneridagh — APPROVED** [review]
@davisagli thanks for looking into this. 

I can confirm that the double `@actions` call happens since a while in vanilla Volto, and given the current architecture is hard to avoid. That's why I haven't pushed more. There's an issue open: https://github.com/plone/volto/issues/4263

Just added it to the sprint priorities.

The multilingual side is well covered by the Cypress tests, and it seems @wesleybl already tried it out, so I'd say it's safe to merge.

**Review by sneridagh — CHANGES_REQUESTED** [review]
@davisagli thanks for looking into this. 

I can confirm that the double `@actions` call happens since a while in vanilla Volto, and given the current architecture is hard to avoid. That's why I haven't pushed more. There's an issue open: https://github.com/plone/volto/issues/4263

Just added it to the sprint priorities.

The multilingual side is well covered by the Cypress tests, however, given @wesleybl it has to be reviewed, the LRF should be all lower case (I guess).

**Comment by claytonc** [comment]
I did the same tests as you @wesleybl and everything is fine for me.

I enabled a multilingual site and created the correct structure with the URL http://localhost:3000/pt-br.

```
export default function applyConfig(config) {
  config.settings = {
    ...config.settings,
    isMultilingual: true,
    supportedLanguages: ['pt-br', 'en', 'es'],
    defaultLanguage: 'pt-br',
  };
  return config;
}

```
Captura de tela de 2023-05-10 11-10-29


@davisagli Thanks for fixing this!

**Comment by wesleybl** [comment]
@claytonc on a multilingual site, when I click on the Plone logo, it goes to: http://localhost:3000/pt-BR

**Comment by claytonc** [comment]
> @claytonc on a multilingual site, when I click on the Plone logo, it goes to: http://localhost:3000/pt-BR

Yes, now I see the problem. I was clicking on the language links.

**Comment by claytonc** [comment]
@wesleybl  footer links also has problems.

- http://localhost:3000/pt-BR//pt-br/sitemap
- http://localhost:3000/pt-BR//pt-br/contact-form

- http://localhost:3000/en//en/sitemap
- http://localhost:3000/en//en/contact-form

- http://localhost:3000/es//es/sitemap
- http://localhost:3000/es//es/contact-form

**Comment by davisagli** [comment]
@wesleybl @claytonc Thanks for testing! I'll take a look at those issues later today.

**Comment by davisagli** [comment]
@wesleybl @claytonc I searched for `state.intl.locale` and tried to fix everything that uses it, including the issues you found above. Could you please test again? /cc @sneridagh @ericof 

One thing I learned: momentjs expects the same format as the backend (`pt-br`).

**Comment by davisagli** [comment]
@sneridagh A note about backwards compatibility: My latest changes touch a lot more .jsx files, which increases the risk of colliding with shadows. I think it should be fine and not cause any new issues, because all of the conversion functions leave 2-letter language codes untouched, and language codes with a region weren't working properly before.

**Comment by wesleybl** [comment]
@davisagli looks like you forgot to push.

**Comment by davisagli** [comment]
@wesleybl 🤦 oops, fixed

**Review by wesleybl — APPROVED** [review]
I tested it and now everything works as expected.

**Comment by davisagli** [comment]
@wesleybl That idea occurred to me too, but it was after I already did this and I didn't see any reason it makes a big difference. I suppose it would make it slightly easier to write code that uses moment, since you wouldn't need to import toBackendLang. Any preference, @sneridagh? Aside from that question, I think this is ready.

File: src/components/theme/Footer/Footer.jsx [hunk 1]
```diff
@@ -97,15 +94,7 @@ const Footer = ({ intl }) => {
...
-                      settings.isMultilingual
-                        ? `/${lang}/${
-                            item.url
-                              ? flattenToAppURL(item.url)
-                              : addAppURL(item.id)
-                          }`
-                        : item.url
-                        ? flattenToAppURL(item.url)
-                        : addAppURL(item.id)
+                      item.url ? flattenToAppURL(item.url) : addAppURL(item.id)
```
Comment (sneridagh) [inline src/components/theme/Footer/Footer.jsx:97]: Where did the rest of the code go?

**Review by sneridagh — CHANGES_REQUESTED** [review]
@davisagli only a small thing, see comments. Also, I think we have to document what helper function to use in each circumstance. Wondering if we cannot make the default (the value in the store already one of them (toBackendLang?)

@wesleybl @claytonc @ericof It would be great to have Cypress tests covering this use cases. Both in multilingual are in single language mode, although it doesn't to have to be now. Next week is Beethoven Sprint, a good one if you want to contribute with something.

File: src/components/theme/Footer/Footer.jsx (hunk 1 above)
Comment (davisagli) [reply src/components/theme/Footer/Footer.jsx:97]: This is intentional. While testing I found that the code for multilingual sites was broken, because the lang prefix is already in the item url

**Review by sneridagh — APPROVED** [review]
