### PR TITLE
Search block: fix 'Clear filters' overriding the base query.

### LINKED ISSUE #7271: Search block: 'Clear filters' overrides the criteria
**Describe the bug**
If you have a search block with a criterium and a filter on the same index, and you click 'Clear filters', the criterium is ignored and you see all results.

Before describing more, let me say that I think I have a small fix, and will make a PR in Volto.

**To Reproduce**

1. Create a few items of different types, for example a Page, an Image, and a News Item.
2. Edit any page (or the Plone Site object) and add a Search block.
3. In the search block add a criterium: Type matches any of Page or Image.  Choose at least two, otherwise the facet we add will be useless.
4. Add a Facet for the same field Type. I made it a checkbox with multiple choices, but the default Select is fine too.
5. Still on the edit page, the search results seem to ignore the criterium, showing other types as well.
6. Save it.
7. View the page.  The search block will show a number of pages and images (if you created them).
8. You will see "Current filters applied: 1" and a button "Clear filters".  Click this button.

**Expected behavior**
After clearing filters, you only see pages and images in the search result.

**What actually happens**
You see *all* items, so including for example news items and the Plone Site object.

**Screenshots**
On the edit page add a search block with this criterium in the base query:

Image

and a facet (filter):

Image

At that point, the edit page already shows all results, instead of applying the base query:

Image

Initial page view:

Image

After clicking on 'Clear filters':

Image

**Further tests**
* If you add a second criterium, all is well: this criterium will always be applied even when clearing filters.
* Add a corresponding filter for the second criterium, and the result is wrong again.

**Software:

- Browser: tested in Firefox and Safari
- Volto 18.23.0 and current 18.x.x branch
- Plone 6.1.1 and current coredev 6.1 branch
- Plone REST API 9.13.3 and current main branch

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Closes #7271.

- [x] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [x] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [x] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [x] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [x] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [ ] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [ ] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [x] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

### CODE REVIEW

File: packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx [hunk 1]
```diff
@@ -42,7 +42,8 @@ const blockPropsAreChanged = (prevProps, nextProps) => {
   return isEqual(prev, next);
 };
 
-const applyDefaults = (data, root) => {
+const applyDefaults = (data, root, block_query) => {
```
Comment (wesleybl) [inline packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx]: Javascript uses camelCase. So it's better to use `blockQuery`. For other variables as well.

File: packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx [hunk 2]
```diff
@@ -42,7 +42,8 @@ const blockPropsAreChanged = (prevProps, nextProps) => {
...
+  block_query = block_query?.length ? block_query : [];
```
Comment (wesleybl) [inline packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx]: It is better to define a new variable than to modify the parameter.

```suggestion
  const normalizedBlockQuery = blockQuery?.length ? blockQuery : [];
```

File: packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx [hunk 3]
```diff
@@ -66,11 +68,29 @@ const applyDefaults = (data, root) => {
...
+  // We start with the base query from the block.
+  // We enhance it with the query from the facets (filters).
+  // We fall back to the default query.
+  let query = block_query;
+  if (!query.length) {
+    query = data_query.length ? data_query : defaultQuery;
+  } else if (data_query.length) {
+    // We have both a base query and a filter.  Combine them.
+    // Items in the filter win over items in the base query.
+    const filter_keys = data_query.map((obj) => obj.i);
```
Comment (wesleybl) [inline packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx]: Use Set for best performance:

```suggestion
    const filterKeys = new Set(dataQuery.map((obj) => obj.i));
```

File: packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx [hunk 4]
```diff
@@ -66,11 +68,29 @@ const applyDefaults = (data, root) => {
...
+    query = data_query.slice();
+    for (const item of block_query) {
+      if (!filter_keys.includes(item.i)) {
+        query.push(item);
+      }
+    }
```
Comment (wesleybl) [inline packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx]: Use spread:

```suggestion
    query = [
      ...dataQuery,
      ...normalizedBlockQuery.filter((item) => !filterKeys.has(item.i))
    ];
```

File: packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx [hunk 5]
```diff
@@ -66,11 +68,29 @@ const applyDefaults = (data, root) => {
...
+  }
+
   return {
     ...data,
     ...sort_on,
     ...sort_order,
-    query: data?.query?.length ? data.query : defaultQuery,
+    query: query,
```
Comment (wesleybl) [inline packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx]: This is redundant. Just use `query`.

**Review by wesleybl — CHANGES_REQUESTED** [review]

**Comment by wesleybl** [comment]
@mauritsvanrees I usually do it in `main` first and then I do a backport to `18.x.x`.

**Comment by mauritsvanrees** [comment]
Thanks for the review and the hints @wesleybl.  I have incorporated your suggestions.  Can you have another look please?

> I usually do it in main first and then I do a backport to 18.x.x.

I usually first fix it on the branch where I need it, and then port it to other branches where needed. :-)

File: packages/volto/news/7271.bugfix.md [hunk 6]
```diff
@@ -0,0 +1 @@
+Search block: fix 'Clear filters' overriding the base query. @mauritsvanrees
```
Comment (wesleybl) [inline packages/volto/news/7271.bugfix.md:1]: Rename it to `.bugfix`

Comment (wesleybl) [reply packages/volto/news/7271.bugfix.md:1]: That's ok. See: https://github.com/plone/volto/pull/7312#discussion_r2324014385

**Comment by wesleybl** [comment]
@davisagli @mauritsvanrees Can you please merge it here? I tested it and it worked!

**Comment by wesleybl** [comment]
Thanks @mauritsvanrees !
