### PR TITLE
Fix autopopulated value of facet when settings the value for another

### LINKED ISSUE #5432: Search block facet value autopopulated with listing criteria value when you select other facet value.
The value of the facet is filled automatically. I haven't selected the facet value and it appears automatically when I selected the other facet value.

1. Create a search block.
2. In listing criteria select the review state and it's value. You can see the screenshot below.
3. After that in first facet select the review state once again.
4. In the second facet select the Type and save the page.
5. Go in view mode and change the Type facet to select a value a value like `Event`.

You will see the review state facet is filled automatically. Which is the bug.

https://github.com/plone/volto/assets/33936987/b45fe2c9-8d22-4ee7-8f51-80e7d214ad41

### PR DESCRIPTION
**Pull request by iFlameing**
…one.

Fixes #5432 

@tiberiuichim Can you please review it.

### CODE REVIEW

**Comment by sneridagh** [comment]
@iFlameing still a draft and WIP or is it ready to review?

**Comment by iFlameing** [comment]
@sneridagh  @tiberiuichim Ready for review now.

File: packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx [hunk 1]
```diff
@@ -96,9 +96,26 @@ function normalizeState({
   const { types: facetWidgetTypes } =
     config.blocks.blocksConfig.search.extensions.facetWidgets;
 
+  // Here we are removing the QueryString of the Listing ones which is persent in the Facet
```
Comment (tiberiuichim) [inline packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx:99]: typo

Comment (tiberiuichim) [reply packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx:99]: Please make this comment more intelligible

File: packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx [hunk 2]
```diff
@@ -96,9 +96,26 @@ function normalizeState({
...
+  // because we already initialize the facet with those value.
+  const configuredFacets = facetSettings
+    ? facetSettings.map((facet) => facet?.field?.value)
+    : [];
+
+  let copyOfQuery = query.query ? [...query.query] : [];
+
+  for (let value of configuredFacets) {
```
Comment (tiberiuichim) [inline packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx:107]: If I understand correctly, I think we can use a list filter for this whole code block, which would simplify it and make  easier to understand.

File: packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx [hunk 3]
```diff
@@ -288,8 +325,17 @@ const withSearch = (options) => (WrappedComponent) => {
     );
     const previousUrlQuery = usePrevious(urlQuery);
 
+    // During first render the previousUrlQuery is undefined and urlQuery
+    // is empty so it ressetting the facet when you are navigating but during reload we have urlQuery and we need
+    // to set the facet at first render.
+    const preventOverrideOfFacetState =
+      previousUrlQuery === undefined && urlQuery.length === 0;
```
Comment (tiberiuichim) [inline packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx:332]: I think trying to make decision here based on some previous state is not a good way to do things. In general. It makes the working of the block harder to reason about (because you introduce time-traveling by looking at the previous state), and harder to replicate, etc.

Now, I am guily of doing this as well, in other cases. But I always feel that it's not a good path to go.

Comment (tiberiuichim) [inline packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx:332]: I think trying to make decision here based on some previous state is not a good way to do things. In general. It makes the working of the block harder to reason about (because you introduce time-traveling by looking at the previous state), and harder to replicate, etc.

Now, I am guily of doing this as well, in other cases. But I always feel that it's not a good path to go.

Comment (iFlameing) [reply packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx:327]: Please suggest to me or give me a pointer to avoid this. I am not able to think of any solution.

**Review by tiberiuichim — APPROVED** [review]
