### PR TITLE
Fixed issue of merging block contents upon pressing delete at end of first block with some content 

### LINKED ISSUE #7263: Pressing Delete at the end of a text-block duplicates the next text-block
When you have two text-blocks (A and B) and press Delete at the end of A the content of B is appended to A but B is still there. 

**Expected behavior**
The second block should disappear.

You can see that on https://volto.demo.plone.org and https://demo.plone.org

### PR DESCRIPTION
**Pull request by aryan7081**
Fixes #7263 

Inside the `joinWithNextBlock `function of `packages/volto-slate/src/blocks/Text/keyboard/joinBlocks.js`, pressing Delete at the end of a text block did not properly remove the following block. In some cases it appeared to append the next block’s content without deleting it, and non‑text blocks were not handled.
This happened because the implementation only merged when the next block was a Slate text block and did not reliably update the Volto blocks state to remove the next block, while skipping non‑text blocks entirely.
This fix ensures that when Delete is pressed at the end of a text block, the next text block is merged into the current block and then removed, and if the next block is non‑text (e.g., Description), it is deleted without merging.

### CODE REVIEW

**Comment by aryan7081** [comment]
@wesleybl Here’s the PR for #7263 as discussed in #7373. Please review when you have time.

File: packages/volto-slate/src/blocks/Text/keyboard/joinBlocks.js [hunk 1]
```diff
@@ -124,36 +124,41 @@ export function joinWithNextBlock({ editor, event }, intl) {
...
-  mergeSlateWithBlockForward(editor, otherBlock);
+  const blocksFieldname = getBlocksFieldname(properties);
+  const blocksLayoutFieldname = getBlocksLayoutFieldname(properties);
 
-  // const cursor = JSON.parse(JSON.stringify(editor.selection));
-  const combined = JSON.parse(JSON.stringify(editor.children));
+  // If next block is not a slate text block, delete it
+  if (otherBlock['@type'] !== 'slate') {
+    const newFormData = deleteBlock(properties, otherBlockId, intl);
+    ReactDOM.unstable_batchedUpdates(() => {
```
Comment (wesleybl) [inline packages/volto-slate/src/blocks/Text/keyboard/joinBlocks.js]: In React 18, `unstable_batchedUpdates` is not necessary. See:

https://www.dhiwise.com/post/how-to-use-unstable-batchedupdates-to-improve-react-performance#best-practices-for-batch-updates

You can simply call the functions without the wrapper.

**Comment by wesleybl** [comment]
@davisagli  suggested here

https://github.com/plone/volto/issues/7263#issuecomment-3299246352

that if the next block isn't text, it should be deleted. But I find this strange. It could be that the user accidentally pressed delete. I prefer that the delete not delete different blocks of text.

**Comment by davisagli** [comment]
@wesleybl To be honest, I can't remember why I suggested that. It makes sense that delete at the end of a slate block should merge with the next block if it is a slate block (that's non-destructive) but not if the next block is another type (that's destructive and should require the user to do more than press one key)

**Comment by aryan7081** [comment]
@wesleybl I have removed all `ReactDOM.unstable_batchedUpdates` wrappers and also updated the block merge behaviour to only merge if both are Slate blocks on pressing delete, and do nothing if the next block is a non-text block.
Thanks for this[ Reference](https://www.dhiwise.com/post/how-to-use-unstable-batchedupdates-to-improve-react-performance#best-practices-for-batch-updates)

**Comment by sneridagh** [comment]
@wesleybl @aryan7081 A bit of context: watch out with the unstable_batchedUpdates... when we tried to removed it when we moved to React 18, we failed, because it started to have race conditions everywhere.

**Comment by davisagli** [comment]
> A bit of context: watch out with the unstable_batchedUpdates... when we tried to removed it when we moved to React 18, we failed, because it started to have race conditions everywhere.

@sneridagh How can we tell if this is still a problem?

**Comment by sneridagh** [comment]
@davisagli unfortunately, we can't. This part of the code is a bit obscure and we would need someone who understand it, document it, and re-owns it, and eventually refactor it into a better version. This, or we move to Plate. ;)

**Comment by davisagli** [comment]
@sneridagh I'm just trying to figure out what to do with this PR. It sounds like it would probably be safest to re-add unstable_batchedUpdates

**Comment by sneridagh** [comment]
@davisagli by all means, we should not touch it, keep the `unstable_batchedUpdates` if nobody steps up for doing that.

**Comment by aryan7081** [comment]
@davisagli @sneridagh @wesleybl I have re-added `unstable_batchUpdates`. Also, `ReactDOM.unstable_batchedUpdates` is actively used throughout the Volto codebase, keeping it here seems logical for now.

**Comment by aryan7081** [comment]
@davisagli @sneridagh @wesleybl, Could someone help me pass the acceptance test? It is shocking for me why `packages/volto/cypress/tests/core/volto-slate/09-block-slate-slashmenu.js` is failing here. I tested running it locally and it passed there also it is unrelated to changes of this PR.

**Comment by wesleybl** [comment]
> A bit of context: watch out with the unstable_batchedUpdates... when we tried to removed it when we moved to React 18, we failed, because it started to have race conditions everywhere.

@sneridagh This is strange. I see several places that recommend removing `unstable_batchedUpdates` in React 18. Even the React folks recommend removing it:

https://github.com/facebook/react/issues/15080#issuecomment-1082480278

**Comment by wesleybl** [comment]
> Could someone help me pass the acceptance test? It is shocking for me why packages/volto/cypress/tests/core/volto-slate/09-block-slate-slashmenu.js is failing here. I tested running it locally and it passed there also it is unrelated to changes of this PR.

@aryan7081 I believe this will solve the problem:

https://github.com/plone/volto/pull/7503

File: packages/volto-slate/news/7263.bugfix [hunk 2]
```diff
@@ -0,0 +1 @@
+Ensure Delete at end of a text block merges the next text block and removes it; if the next block is non-text (e.g., Description), delete it without merging. Adds Cypress coverage. @aryan7081
```
Comment (wesleybl) [inline packages/volto-slate/news/7263.bugfix]: Cypress was made in Volto. So that part can be removed here.

File: packages/volto/cypress/tests/core/blocks/blocks-slate-delete.js [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+    });
+    cy.visit('/my-page');
+    cy.wait('@content');
+    cy.navigate('/my-page/edit');
+    cy.wait('@schema');
+  });
+
+  it('Delete at end of A merges B text block into A and removes B', () => {
+    cy.getSlate().click().typeWithDelay('First block text');
+    cy.getSlate().should('contain', 'First block text');
```
Comment (wesleybl) [inline packages/volto/cypress/tests/core/blocks/blocks-slate-delete.js]: You can use `cy.getSlateEditorAndType` See: https://github.com/plone/volto/blob/835e9f173f4e7eb07ed87925f3de4bad95a50a30/packages/volto/cypress/support/commands.js#L835

In other places too.

File: packages/volto/cypress/tests/core/blocks/blocks-slate-delete.js [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+
+    cy.addNewBlock('slate');
+    cy.getSlateEditorAndType('Second block text');
+
+    cy.get(
+      '.content-area .block-editor-slate .slate-editor [contenteditable=true]',
+      { timeout: 8000 },
```
Comment (wesleybl) [inline packages/volto/cypress/tests/core/blocks/blocks-slate-delete.js:26]: You can use `cy.getSlateEditorSelectorAndType` See:

https://github.com/plone/volto/blob/835e9f173f4e7eb07ed87925f3de4bad95a50a30/packages/volto/cypress/support/commands.js#L845

In other places too.

**Comment by aryan7081** [comment]
@wesleybl Thank you so much for your guidance. The tests have passed, and I have committed the requested changes.

File: packages/volto-slate/news/7263.bugfix [hunk 5]
```diff
@@ -0,0 +1 @@
+Ensure Delete at end of a text block merges the next text block and removes it; if the next block is non-text (e.g., Description), delete it without merging. @aryan7081
```
Comment (wesleybl) [inline packages/volto-slate/news/7263.bugfix]: No longer delete the next block if it is not a text block.

Comment (aryan7081) [reply packages/volto-slate/news/7263.bugfix]: I have updated the logic to skip deletion for non-text blocks and updated the change log entry accordingly.

**Comment by wesleybl** [comment]
@aryan7081 Thanks!

Could you please backport to the 18.x.x branch?

**Comment by aryan7081** [comment]
@wesleybl Sure, I'll prepare a backport to Volto 18.
Thanks and Regards!
