### PR TITLE
Fix Toolbar Types crash when language code is missing in langmap (#7637)

### LINKED ISSUE #7637: Toolbar Types crashes when language code not in langmap
# Bug Report: Toolbar Types crashes when language code not in langmap

## Describe the bug

The Toolbar Types component crashes with `TypeError: Cannot read properties of undefined (reading 'nativeName')` when trying to display translation options for content in a multilingual site. This occurs when Plone's configured available languages include a language code that is not defined in Volto's LanguageMap.

The error prevents users from interacting with the "Add Translation" feature in the toolbar, causing the entire UI to crash with an error overlay.

## To Reproduce

1. **Configure Plone with a language not in Volto's langmap:**
   - Go to 'Site Setup' → 'Language Settings' (or `http://localhost:3000/controlpanel/language`)
   - Add a language that exists in Plone but not in Volto's LanguageMap
   - Example: `fr-ht` (Haitian French/Creole)
   - Save the language settings
   
2. **Install multilingual support:**
   - Go to 'Site Setup' → 'Add-ons' (`http://localhost:3000/controlpanel/addons`)
   - Install `plone.app.multilingual` addon
   - Wait for installation to complete

3. **Create any content:**
   - Navigate to site root or any folder
   - Click 'Add' button in the toolbar
   - Create a Document (or any content type)
   - Fill in title: "Test Content"
   - Save the content

4. **Trigger the error:**
   - Click on the content item you just created
   - Click the 'Add' button in the toolbar (top-right corner)
   - Observe the "Add Translation…" section trying to render
   - **See error overlay appear immediately**

## Expected behavior

The toolbar should handle missing language codes gracefully:

1. The "Add Translation" menu should display successfully
2. For languages not in the langmap, it should:
   - Either display the language code itself (e.g., "Translate to fr-ht")
   - Or display a fallback name
   - Or skip/hide unavailable languages
3. The UI should NOT crash
4. Users should be able to continue working with available languages

## Screenshots

**Error Overlay:**
```
×
←→1 of 2 errors on the page
TypeError: Cannot read properties of undefined (reading 'nativeName')
(anonymous function)
src/components/manage/Toolbar/Types.jsx:98
   95 |     id="Translate to {lang}"
   96 |     defaultMessage="Translate to {lang}"
   97 |     values={{
>  98 |       lang: langmap[lang].nativeName.toLowerCase(),
      | ^   99 |     }}
  100 |   />
  101 | </Link>
```

**Full Stack Trace:**
```
TypeError: Cannot read properties of undefined (reading 'nativeName')
    at Types (http://localhost:3001/static/js/client.js:96505:3)
    at ConnectFunction (http://localhost:3001/static/js/client.js:185763:103)
    at div
    at div
    at Toolbar (http://localhost:3001/static/js/client.js:95834:5)
    at ConnectFunction (http://localhost:3001/static/js/client.js:185763:103)
    at CookieWrapper (http://localhost:3001/static/js/client.js:136870:51)
    at withCookies(Connect(Toolbar))
    at injectIntl(withCookies(Connect(Toolbar)))
    at div
    at View (http://localhost:3001/static/js/client.js:112678:5)
    at ConnectFunction (http://localhost:3001/static/js/client.js:185763:103)
    at injectIntl(Connect(View))
    at Route (http://localhost:3001/static/js/client.js:188891:29)
    at Switch (http://localhost:3001/static/js/client.js:189097:29)
    ...
```

**Error Page:**
```
Sorry, something went wrong with your request 
Cannot read properties of undefined (reading 'nativeName')
```

Image
Image

## Software (please complete the following information):

- **OS**: Windows 11 / Linux
- **Browser**: Brave 142.0.0.0 (Chromium-based) / Chrome / Firefox / Safari (all browsers affected)
- **Volto Version**: 19.0.0-alpha.13 (also confirmed in main branch)
- **Plone Version**: 6.0.13
- **Plone REST API Version**: Latest (included in Plone 6.0.13)
- **Node Version**: (your Node version)
- **Package Manager**: pnpm 10.20.0

### Root Cause Analysis

**File:** `packages/volto/src/components/manage/Toolbar/Types.jsx`  
**Line:** 98

**Problematic Code:**
```javascript
<FormattedMessage
  id="Translate to {lang}"
  defaultMessage="Translate to {lang}"
  values={{
    lang: langmap[lang].nativeName.toLowerCase(),  // ❌ CRASHES HERE
  }}
/>
```

**Why it crashes:**
- The code assumes `langmap[lang]` always exists
- When `plone.available_languages` includes a language code (e.g., `fr-ht`) that is not defined in `packages/volto/src/helpers/LanguageMap/LanguageMap.js`
- `langmap[lang]` returns `undefined`
- Attempting to access `.nativeName` on `undefined` causes the crash

### Verification

Confirmed this is NOT related to any local changes:
```bash
# Check if Types.jsx was modified
git diff main..HEAD -- packages/volto/src/components/manage/Toolbar/Types.jsx
# Output: (empty) - confirming the bug exists in main branch
```

### Affected Language Codes

This issue affects any language configured in Plone but missing from Volto's LanguageMap, including:

- `fr-ht` (Haitian French/Creole) - **confirmed in my case**
- Many regional language variants
- Minority/indigenous languages
- Custom language codes added to Plone

### Tested Scenario

**Backend Configuration (confirmed via API):**
```json
{
  "plone.available_languages": [
    "en",
    "fr-ht"  // ← This language is not in Volto's langmap
  ],
  "plone.default_language": "en"
}
```

**Volto LanguageMap Check:**
```bash
# Search for fr-ht in langmap
grep -i "fr-ht" packages/volto/src/helpers/LanguageMap/LanguageMap.js
# Exit code: 1 (not found)
```

### Impact

- **Severity**: Medium-High
- **User Impact**: Complete UI crash when trying to use multilingual features
- **Workaround**: Remove unsupported languages from Plone's language settings (not ideal)
- **Affected Users**: Multilingual sites using languages not in Volto's hardcoded langmap

### Proposed Fix

Use optional chaining with a fallback to prevent the crash:

**Option 1 - Defensive with fallback:**
```javascript
lang: langmap[lang]?.nativeName?.toLowerCase() || lang,
```

**Option 2 - Explicit checking:**
```javascript
lang: langmap[lang] 
  ? langmap[lang].nativeName.toLowerCase() 
  : lang,
```

**Option 3 - Filter out unavailable languages:**
```javascript
const translationsLeft = filter(
  availableLanguages,
  (lang) =>
    langmap[lang] &&  // ← Add this check
    !Boolean(
      content['@components'].translations &&
        find(content['@components'].translations.items, {
          language: lang,
        }),
    ) && toBackendLang(currentLanguage) !== lang,
);
```

### Related Issues

- This is **different** from #7309 (which was about `content.language.token`)
- Should check other components using `langmap` for similar unsafe access patterns
- Consider making the langmap more extensible or providing a way to register custom languages

### PR DESCRIPTION
**Pull request by pratyush07-hub**
This fixes a bug where the Toolbar Types component crashes if a language in Plone is not in Volto’s langmap.

This PR fixes the issue by :
- The crash happened because the code assumed langmap[lang] always exists.
- Now, if a language is not in langmap, it will fall back to displaying the language code itself, preventing the toolbar from crashing.

Files changed:
- packages/volto/src/components/manage/Toolbar/Types.jsx
- packages/volto/news/7637.bugfix

Changelog:
- Added a news file documenting this bug fix.

-----

- [x] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [x] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [x] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [x] I successfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [x] I successfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [x] I successfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [x] If needed, I added new tests for my changes.
- [x] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [x] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

Closes #7637 

-----

### CODE REVIEW

**Comment by wesleybl** [comment]
@pratyush07-hub If I add `fr-ht` to the available languages ​​and then install `plone.app.multilingual`, I get the error:

```javascript
Cannot read properties of undefined (reading 'nativeName')

```

I can't even add content afterwards. Perhaps issue #7637 is incomplete?

**Comment by pratyush07-hub** [comment]
> @pratyush07-hub If I add `fr-ht` to the available languages ​​and then install `plone.app.multilingual`, I get the error:
> 
> ```js
> Cannot read properties of undefined (reading 'nativeName')
> ```
> 
> I can't even add content afterwards. Perhaps issue #7637 is incomplete?

I have checked it, and this is an additional issue that is not covered by my PR.
fr-ht doesn’t exist in the language map, so that’s why the error appears.
I’m trying to fix this issue now.

**Comment by pratyush07-hub** [comment]
> @pratyush07-hub If I add `fr-ht` to the available languages ​​and then install `plone.app.multilingual`, I get the error:
> 
> ```js
> Cannot read properties of undefined (reading 'nativeName')
> ```
> 
> I can't even add content afterwards. Perhaps issue #7637 is incomplete?

Hi @wesleybl ,
I recorded a screen demo to show that my original fix works correctly.
The new issue happens only after a reload, and that's when the missing language in langmap causes the nativeName error you mentioned.
I didn’t notice this earlier, but now I understand the cause and I’m currently working on fixing this as well.

[Screencast from 2025-12-05 14-09-58.webm](https://github.com/user-attachments/assets/e546dc6f-9c1f-404f-b959-61ccf03d55ca)

**Comment by pratyush07-hub** [comment]
Hi @wesleybl @stevepiercy ,

I’ve been looking into the crash that happens when Plone has a language that Volto doesn’t recognize in its LanguageMap.

What’s going wrong:
Plone can include languages like "fr-ht", but Volto doesn’t have an entry for them in LanguageMap.
When the UI tries to read langmap[lang].nativeName, it ends up being undefined, which causes Volto to crash.

What I am trying to do:

- In LanguageSelector.tsx, I added a safe fallback so the UI won’t crash. If a language isn’t in the map, it just displays the language code.
- In MultilingualRedirector.jsx, I added checks so unsupported languages in cookies fall back to the default language, and missing locale files don’t cause errors.

However, these fixes alone are not enough.

I need your guidance here:

1. should we show unsupported languages using their code (e.g., “fr-ht”), or
2. should we block them in the selector and prevent users from choosing them.
3. Also, should we consider adding these missing languages to LanguageMap.js?

I am thinking that option 2 might be the better choice, but I’d like your guidance.

**Comment by wesleybl** [comment]
> should we show unsupported languages using their code (e.g., “fr-ht”)

If the backend supports a specific language and the user has selected that language, I think it's best not to have limitations and only display the language code.

I don't think we need to update LanguageMap.js if Volto doesn't support that language.

**Comment by pratyush07-hub** [comment]
hey @wesleybl,

I've updated LanguageSelector so it falls back to showing the language code if nativeName is missing, which fixes the crash.
MultilingualRedirector now reads the language directly from the URL, so languages supported by the backend (like fr-ht) work even if they aren’t in the frontend map.

I also removed the strict LanguageMap filter in Types.jsx, so all backend languages now appear in the translation menu.

Overall, these changes remove unnecessary limits. Users can open any supported language URL without redirects, and if a locale is missing, the UI shows English labels while keeping the correct content language and URL.

File: packages/volto/src/components/manage/Toolbar/Types.jsx [hunk 1]
```diff
@@ -59,12 +59,15 @@ const Types = ({ types, pathname, content, currentLanguage }) => {
           const translationsLeft = filter(
             availableLanguages,
             (lang) =>
+              lang &&
+              lang &&
```
Comment (wesleybl) [inline packages/volto/src/components/manage/Toolbar/Types.jsx]: That's not necessary.

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx [hunk 2]
```diff
@@ -18,20 +23,63 @@ const MultilingualRedirector = (props) => {
...
+          .then((locale) => {
+            if (mounted) {
+              dispatch(changeLanguage(redirectToLanguage, locale.default));
+            }
+          })
+          .catch(() => {
+            // eslint-disable-next-line no-console
+            console.warn(
+              `Locale file for ${redirectToLanguage} not found. Fallback to default.`,
+            );
```
Comment (wesleybl) [inline packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx]: This will clutter the console and slow it down. It's better to leave it without logs.

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx [hunk 3]
```diff
@@ -18,20 +23,63 @@ const MultilingualRedirector = (props) => {
...
     let mounted = true;
-    if (isMultilingual && pathname === '/') {
-      const langFileName = toGettextLang(redirectToLanguage);
-      import(
-        /* @vite-ignore */ '@root/../locales/' + langFileName + '.json'
-      ).then((locale) => {
-        if (mounted) {
-          dispatch(changeLanguage(redirectToLanguage, locale.default));
+    if (isMultilingual) {
+      if (pathname === '/') {
```
Comment (wesleybl) [inline packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx:43]: Why did you start treatment if we haven't yet reached the root? That's unnecessary. Redirecting treatment should only happen when we're at the root.

**Review by wesleybl — CHANGES_REQUESTED** [review]

File: packages/volto/src/components/manage/Toolbar/Types.jsx (hunk 1 above)
Comment (pratyush07-hub) [reply packages/volto/src/components/manage/Toolbar/Types.jsx]: fixed

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx (hunk 2 above)
Comment (pratyush07-hub) [reply packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx]: fixed

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx (hunk 3 above)
Comment (pratyush07-hub) [reply packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx:43]: fixed

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx [hunk 4]
```diff
@@ -3,13 +3,18 @@ import { Redirect } from 'react-router-dom';
 import { useDispatch, useSelector } from 'react-redux';
 import { useCookies } from 'react-cookie';
 import { changeLanguage } from '@plone/volto/actions/language/language';
+
```
Comment (wesleybl) [inline packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx]: There's no need to skip a line here.

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx [hunk 5]
```diff
@@ -18,20 +23,31 @@ const MultilingualRedirector = (props) => {
...
-        if (mounted) {
-          dispatch(changeLanguage(redirectToLanguage, locale.default));
-        }
-      });
+    if (isMultilingual && pathname !== '/') {
+      const lang = pathname.split('/')[1];
+      if (
+        availableLanguages?.includes(lang) &&
+        lang !== currentLanguage &&
+        mounted
```
Comment (wesleybl) [inline packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx]: This `&& mounted` is not necessary here. It will always be true.

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx [hunk 6]
```diff
@@ -18,20 +23,31 @@ const MultilingualRedirector = (props) => {
...
+        const langFileName = toGettextLang(lang);
+        import(/* @vite-ignore */ '@root/../locales/' + langFileName + '.json')
+          .then((locale) => {
+            if (mounted) {
+              dispatch(changeLanguage(lang, locale.default));
+            }
+          })
+          .catch(() => {
+            if (mounted) {
+              dispatch(changeLanguage(lang, {}));
```
Comment (wesleybl) [inline packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx]: Add a comment here explaining why.

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx [hunk 7]
```diff
@@ -18,20 +23,31 @@ const MultilingualRedirector = (props) => {
...
-    if (isMultilingual && pathname === '/') {
-      const langFileName = toGettextLang(redirectToLanguage);
-      import(
-        /* @vite-ignore */ '@root/../locales/' + langFileName + '.json'
-      ).then((locale) => {
-        if (mounted) {
-          dispatch(changeLanguage(redirectToLanguage, locale.default));
-        }
-      });
+    if (isMultilingual && pathname !== '/') {
```
Comment (wesleybl) [inline packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx]: I don't understand why you changed the condition here?

File: packages/volto/src/components/manage/Toolbar/Types.jsx [hunk 8]
```diff
@@ -59,12 +59,14 @@ const Types = ({ types, pathname, content, currentLanguage }) => {
           const translationsLeft = filter(
             availableLanguages,
             (lang) =>
+              lang &&
```
Comment (wesleybl) [inline packages/volto/src/components/manage/Toolbar/Types.jsx]: This is not necessary.

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx
Comment (wesleybl) [inline packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx:1]: It's not possible to test this because we have another bug, even on the main branch.

If I select Brazilian Portuguese as the default language and as an available language, inside the `pt-br` folder I create a page with a link to `http://localhost:3000`, but when I click the link, it redirects to `http://localhost:3000/pt_BR` instead of `http://localhost:3000/pt-br`.

It would be better to fix this other error in a separate PR instead of this one.

Comment (pratyush07-hub) [reply packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx:1]: > It's not possible to test this because we have another bug, even on the main branch.
> 
> If I select Brazilian Portuguese as the default language and as an available language, inside the `pt-br` folder I create a page with a link to `http://localhost:3000`, but when I click the link, it redirects to `http://localhost:3000/pt_BR` instead of `http://localhost:3000/pt-br`.
> 
> It would be better to fix this other error in a separate PR instead of this one.

Regarding the major bug about the redirection code (pt-br vs. pt_BR):

1. I will open a new, separate Pull Request (PR) right away to fix that language code formatting bug.
2. For this current PR, I have already made the structural changes you requested to fix the logic flow.

Comment (pratyush07-hub) [reply packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx:1]: I can confirm that the language code mismatch issue you identified (e.g., pt-br vs. pt_BR) is also occurring with the fr-ht locale (generating fr_HT in the URL).

I have included the screenshot for reference:

image

Comment (pratyush07-hub) [reply packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx:1]: Actually, I had identified this earlier and added safety measures so it is not crashing. Previously, it was crashing because it could not find the fr_HT.json file.

**Comment by pratyush07-hub** [comment]
Hey @wesleybl,
I’ve attached a screen recording to show what is currently happening, especially after configuring things as you suggested.

When I select Brazilian Portuguese as the default language and also as an available language, and then create a page inside the pt-br folder with a link pointing to http://localhost:3000, clicking that link redirects to:

http://localhost:3000/pt_BR

instead of:

http://localhost:3000/pt-br

After my recent changes, it now redirects to /en (as per the previous update), but as you mentioned earlier, on the main branch it was redirecting to pt_BR and not pt-br.

I’ve recorded the screen after applying my code changes so you can see the exact behavior and all the related changes. Please review it and let me know how we can resolve this or if there’s a better approach to handle the locale mapping consistently.

[Screencast from 2025-12-14 14-34-23.webm](https://github.com/user-attachments/assets/d114090e-242b-483d-a6c8-bcf1d8ffbaaa)

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx
Comment (wesleybl) [reply packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx:1]: @pratyush07-hub This issue was resolved in: https://github.com/plone/volto/pull/7725
Please update your branch.

Comment (pratyush07-hub) [reply packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx:1]: Got it, @wesleybl. Updating my branch with #7725 now and check if anything else needs adjustment.

Comment (pratyush07-hub) [reply packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx:1]: > @pratyush07-hub This issue was resolved in: #7725 Please update your branch.

I’ve updated my branch. Let me know if any further changes are needed.

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx [hunk 9]
```diff
@@ -18,21 +22,53 @@ const MultilingualRedirector = (props) => {
...
+          })
+          .catch(() => {
+            // If locale file doesn't exist, still switch language with empty locale
+            if (mounted) {
+              dispatch(changeLanguage(redirectToLanguage, {}));
+            }
+          });
+      } else {
+        const lang = pathname.split('/')[1];
+        if (availableLanguages?.includes(lang) && lang !== currentLanguage) {
```
Comment (wesleybl) [inline packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx]: Use `toBackendLang(currentLanguage)` so that the import is not done on every click.

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx [hunk 10]
```diff
@@ -18,21 +22,53 @@ const MultilingualRedirector = (props) => {
...
+            if (mounted) {
+              dispatch(changeLanguage(redirectToLanguage, locale.default));
+            }
+          })
+          .catch(() => {
+            // If locale file doesn't exist, still switch language with empty locale
+            if (mounted) {
+              dispatch(changeLanguage(redirectToLanguage, {}));
+            }
+          });
```
Comment (wesleybl) [inline packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx]: Create a function to avoid code duplication.

**Review by wesleybl — CHANGES_REQUESTED** [review]

**Review by wesleybl — CHANGES_REQUESTED** [review]
If I follow the steps in the issue without reloading the page and creating the content in the portal's root directory, I still get an error:

```javascript
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
Add.render
src/components/manage/Add/Add.jsx:483
  480 | <Grid.Column>
  481 |   <div className="new-translation">
  482 |     <Menu pointing secondary attached tabular>
> 483 |       <Menu.Item name={translateTo.toUpperCase()} active={true}>
      | ^  484 |         {`${this.props.intl.formatMessage(messages.translateTo, {
  485 |           lang: translateTo,
  486 |         })}`}
```

**Comment by pratyush07-hub** [comment]
> If I follow the steps in the issue without reloading the page and creating the content in the portal's root directory, I still get an error:
> 
> ```js
> TypeError: Cannot read properties of undefined (reading 'toUpperCase')
> Add.render
> src/components/manage/Add/Add.jsx:483
>   480 | <Grid.Column>
>   481 |   <div className="new-translation">
>   482 |     <Menu pointing secondary attached tabular>
> > 483 |       <Menu.Item name={translateTo.toUpperCase()} active={true}>
>       | ^  484 |         {`${this.props.intl.formatMessage(messages.translateTo, {
>   485 |           lang: translateTo,
>   486 |         })}`}
> ```

While checking this, I encountered 2–3 additional errors in the same flow. I’m currently fixing them, as the issue appears to be more complex than initially expected.

[Screencast from 2025-12-25 00-29-53.webm](https://github.com/user-attachments/assets/b7c4d5c8-8eb2-4682-bb4f-62c0e7a99f53)

**Comment by pratyush07-hub** [comment]
I’ve made all the necessary changes, and the issue is now working correctly on my local setup.

**Review by wesleybl — APPROVED** [review]

**Comment by wesleybl** [comment]
@pratyush07-hub Thank you!

Could you please do a backport for Volto 18? Remember that in Volto 18, to set languages ​​and multilingual sites, you need to use the Volto settings. See:

https://github.com/plone/volto/blob/18.x.x/packages/volto/src/config/index.js#L114-L116

**Comment by pratyush07-hub** [comment]
@wesleybl  Sure I will backport this to the 18.x.x branch. I will open a separate PR targeting 18.x.x with the same fix.

**Comment by pratyush07-hub** [comment]
@wesleybl  I have opened a backport PR for this fix targeting the 18.x.x branch: #7759
