### PR TITLE
Fix copying of .well-known directory from public/ in production builds

### LINKED ISSUE #7804: Fix collection of dot-file directories like .well-known in public for security.txt and other files.
plone.org issue https://github.com/plone/plone.org/pull/222

.well-known  is not gathered unless using a razzle.extend.js.  In volto 19 we can fix this with the vendorized Razzle.

### PR DESCRIPTION
**Pull request by Kathrina-dev**
### What I did
Fixed an issue in volto-razzle where the .well-known directory placed in public/ was excluded from production builds due to dotfile filtering during the build process.

### Why
Standard discovery endpoints (for example security.txt or assetlinks.json) rely on the .well-known directory being publicly accessible.
Previously, Volto production builds silently omitted this directory because all dotfiles were ignored, making these endpoints unavailable.

This change explicitly allows .well-known to be copied while keeping the existing behavior of ignoring other dotfiles.

### Checklist
- [x] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [x] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [x] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [x] I successfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [x] I successfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [ ] I successfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [x] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [x] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

Closes #7804 

-----

### Notes for reviewers
- The change is non-breaking
- Existing dotfile exclusion behavior remains unchanged
- .well-known is handled explicitly via a separate copy rule

### CODE REVIEW

File: packages/volto-razzle/config/createConfigAsync.js [hunk 1]
```diff
@@ -1004,16 +1004,32 @@ module.exports = (
...
                 {
                   from: paths.appPublic.replace(/\\/g, '/') + '/**/*',
                   to: paths.appBuild,
                   context: paths.appPath,
                   globOptions: {
+                    dot: false,
                     ignore: [
                       paths.appPublic.replace(/\\/g, '/') + '/index.html',
+                      // Exclude .well-known here so it can be handled explicitly below
+                      paths.appPublic.replace(/\\/g, '/') + '/.well-known/**/*',
```
Comment (stevepiercy) [inline packages/volto-razzle/config/createConfigAsync.js:1017]: Will this regular expression allow the file path of `/.well-known/funding-manifest-urls`?

Would you please add a unit test for this use case, as well as one that tests for blocking other dotfiles at the root and directories unless they already exist?

**Review by stevepiercy — CHANGES_REQUESTED** [review]

File: packages/volto-razzle/config/createConfigAsync.js (hunk 1 above)
Comment (Kathrina-dev) [reply packages/volto-razzle/config/createConfigAsync.js:1017]: Yes, this regex allows all files inside .well-known folder to be accessible after you build Volto. 
I’ll add unit tests to cover:
- allowing `.well-known/*` files
- blocking other dotfiles at the root and in subdirectories

**Comment by stevepiercy** [comment]
@Kathrina-dev thank you for adding tests.

It needs a technical review from the @plone/volto-team, and perhaps @davisagli from the original issue.

This PR relates to another recent issue for [plone.org](https://github.com/plone/plone.org/issues/222), where @erral, @fredvd, and @Fosten participated. @plone/marketing-communications might be interested, as well.

**Comment by Kathrina-dev** [comment]
Alright, thanks for the info!

File: packages/volto-razzle/__tests__/createConfigAsync.test.js [hunk 2]
```diff
@@ -0,0 +1,114 @@
+const createConfigAsync = require('../createConfigAsync');
```
Comment (sneridagh) [inline packages/volto-razzle/__tests__/createConfigAsync.test.js:1]: @Kathrina-dev I think these tests are not running at all, nor in CI. Did you run them?

Comment (Kathrina-dev) [reply packages/volto-razzle/__tests__/createConfigAsync.test.js:1]: You're right. I completely forgot about it. I had created the __test__ folder within the config folder and forgot to correct the import statement after moving the folder under Volto-razzle. Thanks for mentioning. 

I've fixed the import statement but Jest is still not running the test. I moved the test file under Volto and now it's able to detect the file. Should I  keep this test under Volto or Volto-razzle?

Comment (Kathrina-dev) [reply packages/volto-razzle/__tests__/createConfigAsync.test.js:1]: @sneridagh please let me know if I should keep the test in volto or volto-razzle

Comment (wesleybl) [reply packages/volto-razzle/__tests__/createConfigAsync.test.js:1]: @Kathrina-dev Ideally, you would add a Vite configuration to the package. See for example: https://github.com/plone/volto/blob/main/packages/volto/vitest.config.mjs

Comment (Kathrina-dev) [reply packages/volto-razzle/__tests__/createConfigAsync.test.js:1]: okay I'll add a vitest test in volto and keep the current jest test in volto-razzle
