### PR TITLE
fixing Markdown heading

### LINKED ISSUE #6577: Markdown heading does not correspond to right HTML Section Heading elements
**Describe the bug**
A single # in the textblock generates a h2 in HTML. It is not a direct bug but a wrong implementation of Markdown, as it is intentional in there. 

https://github.com/plone/volto/blob/467e0a3fe71e711e781fe678979e05c9f46a64e5/packages/volto-slate/src/editor/plugins/Markdown/constants.js#L23-L31

I know that you want to limit titles to an h2 heading, but a user may expect to have an h1 with single #.

**To Reproduce**

1. Create a heading in a text field with a # 
2. Inspect the Element with the Developer Tools
3. You see the mismatch between documentation, the generated HTML and the specification

**Expected behavior**

A single # should generate a h1 and two # should generate a h2 etc.

As stated in the specification:
https://spec.commonmark.org/0.31.2/#atx-heading
or here
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#headings

**Screenshots**
markdown_error

**Software (please complete the following information):**

- OS: Linux
- Browser: Chrome (Version 131.0.6778.264 (Official Build) (64-bit))
- Volto 18.4.0
- Plone 6.1.0b2
- plone.restapi 9.9.0

**Additional context**
There is the intention to prevent the editor from creating to much h1 headings so it is not clearly a bug but a feature, but it is wrong implementation.

### PR DESCRIPTION
**Pull request by Shyam-Raghuwanshi**
- [X] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [X] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [X] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [X] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [X] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [X] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [X] If needed, I added new tests for my changes.
- [X] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [X] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

Closes #6577

### CODE REVIEW

File: packages/volto-slate/src/editor/plugins/Markdown/constants.js [hunk 1]
```diff
@@ -22,13 +30,17 @@ export const localToggleList = (editor, format) => {
  */
 export const autoformatRules = [
   {
-    type: H2,
+    type: H1,
     markup: '#',
   },
```
Comment (davisagli) [inline packages/volto-slate/src/editor/plugins/Markdown/constants.js:35]: We don't want users to be able to add an H1 by typing `#`. The title block creates an H1 and there should not be other headings at that level of the hierarchy.

**Review by davisagli — CHANGES_REQUESTED** [review]
This PR needs a changelog entry. See https://6.docs.plone.org/contributing/index.html#change-log-entry

File: packages/volto-slate/src/editor/plugins/Markdown/constants.js (hunk 1 above)
Comment (Shyam-Raghuwanshi) [reply packages/volto-slate/src/editor/plugins/Markdown/constants.js:35]: yes, You're right

File: packages/volto/news/6588.feature.rst
Comment (davisagli) [inline packages/volto/news/6588.feature.rst:1]: @Shyam-Raghuwanshi Rename to 6588.feature, not 6588.feature.rst

File: packages/volto/news/6588.feature.rst [hunk 2]
```diff
@@ -0,0 +1 @@
+- Added Markdown heading
```
Comment (davisagli) [inline packages/volto/news/6588.feature.rst:1]:
```suggestion
Fixed keyboard shortcuts for typing headings using Markdown notation. @Shyam-Raghuwanshi 
```

File: packages/volto-slate/src/editor/plugins/Markdown/constants.js (hunk 1 above)
Comment (davisagli) [reply packages/volto-slate/src/editor/plugins/Markdown/constants.js:35]: @Shyam-Raghuwanshi This hasn't been resolved. You have to remove lines 32-35.

**Review by davisagli — CHANGES_REQUESTED** [review]

File: packages/volto-slate/src/editor/plugins/Markdown/constants.js (hunk 1 above)
Comment (Shyam-Raghuwanshi) [reply packages/volto-slate/src/editor/plugins/Markdown/constants.js]: O, sorry

File: packages/volto/news/6588.feature
Comment (davisagli) [inline packages/volto/news/6588.feature:1]: I just realized, this needs to be moved to packages/volto-slate/news/6588.feature because the actual change was in volto-slate.

**Review by davisagli — CHANGES_REQUESTED** [review]

**Comment by davisagli** [comment]
@Shyam-Raghuwanshi Almost there!

There is some help text in the text block sidebar which needs to be updated:
Screenshot 2025-01-17 at 9 44 37 PM

Here is the file that needs to be updated: https://github.com/plone/volto/blob/main/packages/volto-slate/src/blocks/Text/MarkdownIntroduction.jsx#L17-L22

**Comment by Shyam-Raghuwanshi** [comment]
@davisagli done

**Review by davisagli — APPROVED** [review]
Thanks! I'll merge once the CI builds finish.
