### PR TITLE
Multilingual Support in contents tab bugfix

### LINKED ISSUE #8140: Multilingual Support messes link up in contents tab
**Describe the bug**
When adding the addon "Multilingual Supoort" and setting two available languages in the "Language" setting to create two language root folders, the language root folder breadcrumbs in "Contents" behave weird. 
When in the "Contents" tab the language breadcrumbs don't bring you to the correct link. 
Instead they duplicate a part of the link so it looks like this: http://localhost:3000/en/http://localhost:3000/en/contents

Image

and you get this error.

**To Reproduce**

1. Create a Plone site
2. Go to site-setup -> "Add-Ons"
3. Add "Multilingual Support"
4. Go back to the site-setup -> "Languages"
5. Add at two available languages and set a site language
6. Go to ["Contents"](http://localhost:3000/en/contents) 
7. Click on the language breadcrumb(in my case English)
8. See the error and the messed up link.

**Expected behavior**A clear and concise description of what you expected to happen.
I expect to get routed to the language folder if I am not already there. I expect the link to not duplicate the first whole part.

**Screenshots**f applicable, add screenshots or videos to help explain your problem.

Image
As you can see in the down-left corner link-preview the link duplicates its first part.

**Software (please complete the following information):**- OS: [e.g. iOS]
- Browser: Chrome
- Volto Version: 19.0.0-alpha.29
- Plone Version: 6.2.0rcl
- Plone REST API Version: 10.0.0rcl

This might be related to #8102

### PR DESCRIPTION
**Pull request by TimoBroeskamp**
- [x] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [x] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [x] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [x] I successfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [x] I successfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [x] I successfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [ ] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [x] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

Closes #8140

-----

If your pull request includes changes to the documentation—either in narrative documentation, Storybook, or configuration—then a pull request preview will be generated and a link will populate in the description of your pull request below.
By clicking that link, you can use the visual diff menu in the upper right corner to navigate to pages that have changes, then display the diff by checking the `Show diff` checkbox.

### CODE REVIEW

File: packages/volto/src/components/manage/Contents/ContentsBreadcrumbs.jsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ const ContentsBreadcrumbs = (props) => {
           </Link>
           <Breadcrumb.Divider />
           <Link
-            to={`${navroot?.['@id']}/contents`}
+            to={`/${navroot?.['@id'].split('/').pop()}/contents`}
```
Comment (davisagli) [inline packages/volto/src/components/manage/Contents/ContentsBreadcrumbs.jsx]: @TimoBroeskamp This doesn't make sense to me.

If the navigation root is at /some/subpath, this will try to link to /subpath/contents which doesn't exist.

You're making the assumption that the navroot path is always a direct child of the Plone site root, but that is not always true.

Instead, you have 2 options here:
1. Use our existing utility for converting a full URL from the backend to a frontend path: flattenToAppURL
2. Use the UniversalLink component instead of Link. It takes care of calling flattenToAppURL.

Probably all of these Links should be UniversalLinks. That way it navigates using the Volto router instead of completely reloading the page.

**Review by davisagli — CHANGES_REQUESTED** [review]

File: packages/volto/src/components/manage/Contents/ContentsBreadcrumbs.jsx (hunk 1 above)
Comment (TimoBroeskamp) [reply packages/volto/src/components/manage/Contents/ContentsBreadcrumbs.jsx]: @davisagli Okay I made some changes and used UniversalLink. This should be fine now but if something is still off to you let me know.

File: packages/volto/news/8140.bugfix [hunk 2]
```diff
@@ -0,0 +1 @@
+Fix for Multilingual Support messed up breadcrumbs in contents tab. @TimoBroeskamp
```
Comment (davisagli) [inline packages/volto/news/8140.bugfix]:
```suggestion
Fixed the link to the navigation root in the Contents view breadcrumbs. @TimoBroeskamp
```

**Review by davisagli — APPROVED** [review]
I tested the fix locally by creating a subsite content type with the navigation root behavior enabled. It works well!

**Comment by wesleybl** [comment]
@TimoBroeskamp Could you please do a backport to Volto 18?
