### PR TITLE
Hide date/time fields when whole_day or open_end is checked in Event form

### LINKED ISSUE #3243: Event: "whole day" and "open end" have no effect
**Describe the bug**

In Plone Classic the UI for the start/end date adapts if the user checks the "whole day" checkbox (time fields disappear) and the "open end" checkbox (end date/time disappear). This is not the case in Volto and this confuses our editors.

Sprints-—-Plone-Enterprise-Level-CMS-Free-and-OpenSource-Community-Driven-Secure

Sprints-—-Plone-Enterprise-Level-CMS-Free-and-OpenSource-Community-Driven-Secure (1)

**To Reproduce**

1. As admin
2. Go to https://volto.kitconcept.dev
3. Create a new event https://volto.kitconcept.dev/add?type=Event
4. Click the "whole day" or "open end" checkbox in the right column
5. Nothing changes in the UI

**Expected behavior**

- When the user checks the "whole day" checkbox, the time fields dissapear
- When the user checks the "open end" checkbox, the end date/time field dissapear

**Screenshots**

Add-Event (1)

**Software (please complete the following information):**

- Plone Version 15.2.1

### PR DESCRIPTION
**Pull request by wesleybl**
- whole_day hides start and end time pickers
- open_end hides end date and end time fields
- Add Cypress test for checkbox behavior

The behavior now:

[chrome-capture-2025-11-27.webm](https://github.com/user-attachments/assets/15291fae-937b-44d8-b9ea-523ef514d824)

Closes #3243

### CODE REVIEW

File: packages/volto/src/components/manage/Widgets/DatetimeWidget.jsx [hunk 1]
```diff
@@ -106,12 +107,17 @@ const DatetimeWidgetComponent = (props) => {
...
+    return null;
+  }
+
   const getInternalValue = () => {
     return parseDateTime(toBackendLang(lang), value, undefined, moment.default);
   };
 
   const getDateOnly = () => {
-    return dateOnly || widget === 'date';
+    return dateOnly || widget === 'date' || formData?.whole_day;
```
Comment (davisagli) [inline packages/volto/src/components/manage/Widgets/DatetimeWidget.jsx]: Let's be a bit more careful here and only check this if the id is 'start'. (It should be possible to add new custom datetime fields to an Event and not have them coupled to the value of `whole_day`.)

File: packages/volto/news/3243.bugfix [hunk 2]
```diff
@@ -0,0 +1 @@
+Hide date/time fields when whole_day or open_end is checked in Event form. @wesleybl
```
Comment (stevepiercy) [inline packages/volto/news/3243.bugfix]:
```suggestion
Hide date and time fields when either "Whole Day" or "Open End" is checked in the Event form. @wesleybl
```

File: packages/volto/src/components/manage/Widgets/DatetimeWidget.jsx (hunk 1 above)
Comment (wesleybl) [reply packages/volto/src/components/manage/Widgets/DatetimeWidget.jsx]: Done

**Review by stevepiercy — APPROVED** [review]
News LGTM. Thank you!
