### PR TITLE
fix: concatenate multilingualRoutes and externalRoutes (if available) to defaultRoutes

### LINKED ISSUE #3653: Default routes provided by the generator don't include everything
https://github.com/plone/volto/blob/05162223a7c08000f3cf86b8ebdd784cbef04fe7/packages/generator-volto/generators/app/templates/src/routes.js#L7

As you see, in the `routes.js` the generator uses the `default_routes`. But the multilanguage routes are not included in the default routes, which is a problem. 

All these:

https://github.com/plone/volto/blob/05162223a7c08000f3cf86b8ebdd784cbef04fe7/src/routes.js#L272

and https://github.com/plone/volto/blob/05162223a7c08000f3cf86b8ebdd784cbef04fe7/src/routes.js#L266-L269

should be moved in the default routes.

### PR DESCRIPTION
**Pull request by erral**
Fixes #3653

### CODE REVIEW

File: src/routes.js [hunk 1]
```diff
@@ -85,10 +85,8 @@ export const multilingualRoutes = [
   },
 ];
 
-export const defaultRoutes = (
-  (config.settings?.isMultilingual && multilingualRoutes) ||
-  []
-).concat([
+export const defaultRoutes = [
+  ...((config.settings?.isMultilingual && multilingualRoutes) || []),
```
Comment (erral) [inline src/routes.js:89]: :upside_down_face:

**Review by ionlizarazu — APPROVED** [review]

**Comment by tiberiuichim** [comment]
May I suggest to move also the external routes fix? Otherwise it's only a partial fix. I know that CodeSyntax worked on the multilingual, but I don't think there are any boundaries when it comes to Volto codebase.

**Comment by erral** [comment]
No problem with that, I moved them to the defaultRoutes

**Review by sneridagh — APPROVED** [review]
