### PR TITLE
fixing Multilingual redirect uses wrong locale format for pt-br

### LINKED ISSUE #7710: Multilingual redirect uses wrong locale format for pt-br
**Describe the bug**
When Brazilian Portuguese (pt-br) is set as the default and available language in Plone with multilingual support enabled, Volto redirects to an incorrect language URL format. Instead of using pt-br, it redirects to pt_BR.

**To Reproduce**

1.Go to Site Setup → Language Settings
    (http://localhost:3000/controlpanel/language)
2.Add pt-br as an available language and set it as the default language. Save the settings.
3.Go to Site Setup → Add-ons
    (http://localhost:3000/controlpanel/addons)
4.Install plone.app.multilingual and wait for the installation to complete.
5.Create a page inside the pt-br language folder.
6.Add a link on the page pointing to:
    http://localhost:3000
7.Click the link.
8.The link redirect to: http://localhost:3000/pt_BR

**Expected behavior**
The link should redirect to: http://localhost:3000/pt-br

**Screenshots / video**
A short video demonstrating the issue is attached.

https://github.com/user-attachments/assets/c5c4406f-f921-47f1-b1e0-3bc47276f39b

**Software (please complete the following information):**

- Browser [e.g. firefox, chrome, safari]
- Volto Version [e.g. 18.4.0]
- Plone Version [e.g. 6.1.0]
- Plone REST API Version [e.g. 9.1.0]

**Additional context**
This issue is related to an existing issue: (Related - #7637 )

### PR DESCRIPTION
**Pull request by Shyam-Raghuwanshi**
- [X] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [X] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [X] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [X] I successfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [X] I successfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [X] I successfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [X] If needed, I added new tests for my changes.
- [X] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [X] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

Closes #7710

### CODE REVIEW

File: packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx [hunk 1]
```diff
@@ -3,15 +3,16 @@ import { Redirect } from 'react-router-dom';
...
 
 const MultilingualRedirector = (props) => {
   const { pathname, children } = props;
   const [cookies] = useCookies();
   const site = useSelector((state) => state.site.data);
   const isMultilingual = site.features?.multilingual;
   const redirectToLanguage =
-    cookies['I18N_LANGUAGE'] || site['plone.default_language'];
+    (cookies['I18N_LANGUAGE'] && toBackendLang(cookies['I18N_LANGUAGE'])) ||
+    site['plone.default_language'];
```
Comment (wesleybl) [inline packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx]: The `useEffect` below requires the language to be in `pt_BR` format. Therefore, it's best to call `toBackendLang` in the `Redirect` component call:

https://github.com/plone/volto/blob/75535698e603713dd56509266a3c0c8b94a67123/packages/volto/src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx#L38

File: packages/volto/news/7725.bugfix [hunk 2]
```diff
@@ -0,0 +1 @@
+Fix multilingual redirect using wrong locale format for pt-br. @Shyam-Raghuwanshi
```
Comment (wesleybl) [inline packages/volto/news/7725.bugfix]: This problem occurs with any language that has a locale, not just pt-br. Please make the message more generic.

**Comment by wesleybl** [comment]
@Shyam-Raghuwanshi Thank you!

Could you please do a backport to the Volto 18? On the Volto 18, to test and indicate that the portal is multilingual, you need to use the Volto configuration:

https://github.com/plone/volto/blob/18.x.x/packages/volto/src/config/index.js#L114-L116

For example:

```
    isMultilingual: true,
    supportedLanguages: ['en', 'pt-br'],
    defaultLanguage: process.env.SITE_DEFAULT_LANGUAGE || 'en',
```

**Comment by Shyam-Raghuwanshi** [comment]
> @Shyam-Raghuwanshi Thank you!
> 
> Could you please do a backport to the Volto 18? On the Volto 18, to test and indicate that the portal is multilingual, you need to use the Volto configuration:
> 
> https://github.com/plone/volto/blob/18.x.x/packages/volto/src/config/index.js#L114-L116
> 
> For example:
> 
> ```
>     isMultilingual: true,
>     supportedLanguages: ['en', 'pt-br'],
>     defaultLanguage: process.env.SITE_DEFAULT_LANGUAGE || 'en',
> ```

sure
