### PR TITLE
Fix slate RichTextwidget to allow support slate extensions refs#6570

### LINKED ISSUE #6570: Allow passing slate extensions to RichTextWidget
**Describe the bug**
The text block configuration in the core can be extended using textBlockExtensions. However, we don't apply this to the RichtextWidget because, in the past, we faced issues with how it handled unordered lists (ul) and list items (li).

**To Reproduce**

1. Try adding a richText widget on a field and add a `ul` with some `li`'s. 
2. It seems you can't go out of lists, also on shift+Enter.

**Expected behavior**
The behaviour should be same as textlock where shift+Enter should go on a newline `\n`, Enter on empty li should come out of list. 

- Volto Version - 18.x also on 17.x

TextBlock: https://github.com/plone/volto/blob/e55b4a65170f0a2038d9d1db994748bca9f72f95/packages/volto-slate/src/blocks/Text/DefaultTextBlockEditor.jsx#L73

https://github.com/plone/volto/blob/e55b4a65170f0a2038d9d1db994748bca9f72f95/packages/volto-slate/src/blocks/Text/index.jsx#L41

RichTextWidget: https://github.com/plone/volto/blob/e55b4a65170f0a2038d9d1db994748bca9f72f95/packages/volto-slate/src/widgets/RichTextWidget.jsx#L63

### PR DESCRIPTION
**Pull request by nileshgulia1**
Closes #6570

### CODE REVIEW

**Comment by nileshgulia1** [comment]
@davisagli Its something which we are also doing it for textBlock. slate-extensions just adds extra capabilities to slate wrapped components. To test this, you can create a RichText widget in your content type, try to create some lists(ul) with few li's, save the page and re-edit them, you see there is no way to get outside of lists, or actually there is no way to add anything else. 
I've created a sample here(on edit ): https://demo.plone.org/test-richtext

Perhaps I should create some E2E tests also 🤔

**Comment by nileshgulia1** [comment]
There is a detached mode also but I think its for blocks not widgets.

**Comment by stevepiercy** [comment]
@nileshgulia1 I don't follow. I can use the up and down arrows to move between blocks.


https://github.com/user-attachments/assets/5d70c9bc-0b92-4ac4-b78e-e80d9ac66ce8

**Review by davisagli — CHANGES_REQUESTED** [review]
@nileshgulia1 @stevepiercy I think I understand the problem better now:
- This is specifically a problem with the rich text widget, not the slate block. To test it, you have to add a rich text field to a content type, and edit there, not in a block.
- The problem is that when you're typing in a list, you would expect to be able to hit Enter a couple times to end the list. But this just creates new list items, and there's no obvious way to add text that is not in the list.

Do I have it right? If so, I'd suggest a different changelog entry here: "Fix typing Enter to end a list in the RichTextWidget." Using a slate extension for this is just an implementation detail, not the point of the change.

Unfortunately, I tested with this PR locally and it doesn't actually seem to fix the problem.

**Comment by davisagli** [comment]
@nileshgulia1 Your video looks like what I would expect! I'll try to step through in the debugger in my local site later this week and see if I can tell why it didn't work for me.

File: packages/volto-slate/src/widgets/HtmlSlateWidget.jsx [hunk 1]
```diff
@@ -127,7 +132,10 @@ const HtmlSlateWidget = (props) => {
             block={block}
             selected={selected}
             properties={properties}
+            extensions={slateWidgetExtensions}
```
Comment (nileshgulia1) [inline packages/volto-slate/src/widgets/HtmlSlateWidget.jsx:135]: I fixed the issue with inconsistency,  htmlSlateWidget is used as `richtext` and we override this in our policy adddon. Thus, the same extension should be ported here as well.

I will write the cypress for this scenario.

Comment (nileshgulia1) [reply packages/volto-slate/src/widgets/HtmlSlateWidget.jsx:135]: -cc @davisagli

File: packages/volto-slate/news/6570.bugfix [hunk 2]
```diff
@@ -0,0 +1 @@
+fix: add extensions in RichtextWidget @nileshgulia1
```
Comment (davisagli) [inline packages/volto-slate/news/6570.bugfix:1]:
```suggestion
In `RichTextWidget` and `HtmlSlateWidget`, fix breaking a list by typing Enter. @nileshgulia1
```

**Review by davisagli — APPROVED** [review]
@nileshgulia1 Thanks, now it does what I expected!

**Comment by nileshgulia1** [comment]
@sneridagh We can merge this please. Thank you.

File: packages/volto/news/6570.internal
Comment (davisagli) [inline packages/volto/news/6570.internal:1]: @nileshgulia1 Use `.internal` for changes that only involve tests. I updated it already.

**Comment by nileshgulia1** [comment]
@davisagli Perhaps this is a candidate for volto 17.x backport?

**Comment by nileshgulia1** [comment]
@davisagli Done, Pls check: https://github.com/plone/volto/pull/6743
