### PR TITLE
Replace spinner with Progress bar and fix it's position . (#5620)

### LINKED ISSUE #5620: Loading indicator (spinner) badly positioned when uploading hundreds of images via folder contents. Replace spinner with upload progress indicator (x of y files uploaded).
**Describe the bug**

When a user uploads hundreds of images (e.g. the Pastanaga icons set https://github.com/plone/pastanaga-icons/tree/main/Icons) she does not see any indication that the site is uploading images in the background. For the user it seems like the site is frozen.

**To Reproduce**

1. As admin
2. Go to demo.plone.org
3. Go to folder_contents (https://demo.plone.org/icons/contents) and drag and drop the Pastanaga UI icon set
4. Click the save button (right arrow)
5. -> there is no spinner visible, the page looks frozen

**Expected behavior**

Show a spinner that shows that the site is still loading. In an ideal world, a progress indicator would show how many files have been uploaded already (e.g. 4 of 345 files have been uploaded).

**Screenshots**

Inhalte (18)

### PR DESCRIPTION
**Pull request by victorchrollo14**
Fixes #5620.

* Replaced the spinner in contents -> upload, With a progress bar that indicates the number of files uploaded. ( Uploaded x out of y files ).
* Fixed the bad positioning of the spinner when a large number of files were uploaded by add a `max-height` and `overflow: auto` which fixes issue ( #5677 ).

### To Implement the progress bar.
* Added a new property of `uploadedFiles` to the contents redux state.
* Added a 'UPDATE_UPLOADED_FILES' type to ActionTypes.js, an action creator and a reducer function for the same.
* Added a local totalFiles state inside `ContetsUploadModal`.
* To update the number of files uploaded we dispatch the `updateUploadedFile`  action inside the redux api middleware, after each of the upload requests are fullfilled. and finally set the uploadedFiles to 0 after all the requests are fulfilled. 
* Added unit tests for the `updateUploadedFile` action creator and the reducer as well.

[Screencast from 26-03-24 06:57:09 PM IST.webm](https://github.com/plone/volto/assets/89346667/28a0f296-0dad-4968-b8a5-b3190f0d2dc9)

### CODE REVIEW

**Comment by stevepiercy** [comment]
I restarted the failed CI check, and we'll [see if it passes](https://github.com/plone/volto/actions/runs/8454968566/job/23173728410?pr=5929) this time.

**Review by stevepiercy — COMMENTED** [review]
That's great that you took the extra effort to provide translations to all those languages. I'll request review from the suggested folks, but anyone who has an interest in getting this merged is welcome to add a review. Thank you!

**Comment by stevepiercy** [comment]
CI is all green. Let's get a review from @plone/volto-team.

**Comment by victorchrollo14** [comment]
> That's great that you took the extra effort to provide translations to all those languages. I'll request review from the suggested folks, but anyone who has an interest in getting this merged is welcome to add a review. Thank you!

Hey @stevepiercy. I didn't add the translations, the earlier message of 'uploading files' got automatically removed after I made the changes, I thought this is normal and committed those changes. 

I'll add the translations and push it up then.

**Review by giuliaghisini — APPROVED** [review]

File: packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx [hunk 1]
```diff
@@ -211,13 +215,13 @@ class ContentsUploadModal extends Component {
...
-              <FormattedMessage
-                id="Uploading files"
-                defaultMessage="Uploading files"
-              />
-            </Loader>
+            <Progress
+              className="progress-bar"
+              value={this.props.uploadedFiles}
+              total={this.state.totalFiles}
+            >{`Uploading: ${this.props.uploadedFiles} Files Out Of ${this.state.totalFiles}`}</Progress>
```
Comment (ichim-david) [inline packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx:224]: @victorchrollo14 you need to add the message with formatMessage using several attributes.
Here is an example of how it's done within Sharing.jsx
https://github.com/plone/volto/blob/main/packages/volto/src/components/manage/Sharing/Sharing.jsx#L90
https://github.com/plone/volto/blob/main/packages/volto/src/components/manage/Sharing/Sharing.jsx#L434
and how it looks when the message is extracted
https://github.com/plone/volto/blob/main/packages/volto/locales/en/LC_MESSAGES/volto.po#L407

We do not want the message to be hardcoded to english since Volto is a multi language framework.

**Review by ichim-david — CHANGES_REQUESTED** [review]

File: packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx (hunk 1 above)
Comment (victorchrollo14) [reply packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx:224]: yeah @stevepiercy mentioned that, I'll add that up.

File: packages/volto/locales/ca/LC_MESSAGES/volto.po [hunk 2]
```diff
@@ -3979,16 +3979,16 @@ msgstr "Pengeu una imatge principal al camp de contingut 'Imatge principal'."
...
-#: components/manage/Contents/ContentsUploadModal
-msgid "Uploading files"
-msgstr "Carregant fitxers"
-
 #. Default: "Uploading image"
 #: components/manage/Blocks/Image/Edit
 msgid "Uploading image"
 msgstr "S'està carregant la imatge"
 
+#. Default: "Uploading {uploadedFiles} Files Out of {totalFiles}"
```
Comment (stevepiercy) [inline packages/volto/locales/ca/LC_MESSAGES/volto.po:3987]: For all instances of this phrase throughout the pull request, not just this one suggestion and file, please use sentence casing.

```suggestion
#. Default: "Uploading {uploadedFiles} files out of {totalFiles}"
```

File: packages/volto/locales/de/LC_MESSAGES/volto.po [hunk 3]
```diff
@@ -3978,16 +3978,16 @@ msgstr "Laden Sie ein Lead-Bild im Feld 'Lead-Bild' hoch."
...
-
 #. Default: "Uploading image"
 #: components/manage/Blocks/Image/Edit
 msgid "Uploading image"
 msgstr "Bild hochladen"
 
+#. Default: "Uploading {uploadedFiles} Files Out of {totalFiles}"
+#: components/manage/Contents/ContentsUploadModal
+msgid "Uploading {uploadedFiles} Files Out of {totalFiles}"
+msgstr "Hochladen von {uploadedFiles} Dateien von insgesamt {totalFiles}"
```
Comment (stevepiercy) [inline packages/volto/locales/de/LC_MESSAGES/volto.po:3989]:
```suggestion
msgstr "Hochladen von {uploadedFiles} dateien von insgesamt {totalFiles}"
```

File: packages/volto/news/5620.bugfix [hunk 4]
```diff
@@ -0,0 +1 @@
+Replaced the spinner with a progress bar that shows the number of files uploaded (Uploaded: x out of y files) and positioned the progress bar properly while uploading a large number of files. @victorchrollo14
```
Comment (stevepiercy) [inline packages/volto/news/5620.bugfix:1]:
```suggestion
Replaced the spinner with a progress bar that shows the number of files being uploaded (Uploading x files out of y), and positioned the progress bar properly, while uploading a large number of files. @victorchrollo14
```

**Review by stevepiercy — CHANGES_REQUESTED** [review]

File: packages/volto/locales/ca/LC_MESSAGES/volto.po (hunk 2 above)
Comment (victorchrollo14) [reply packages/volto/locales/ca/LC_MESSAGES/volto.po:3987]: okay. I'll change this up.

**Review by stevepiercy — APPROVED** [review]
Messages look good now. Let's get one more review from a @plone/volto-team member.

**Comment by ichim-david** [comment]
@victorchrollo14 the feature looks like it works based on your recording. I wouldn't be surprised if you won't receive feedback to tweak the styles or for us todo so after merging.
I would still like to test it and see how it performs and it might take a while until this is merged but I have a good feeling about this one, congratulations.

**Comment by victorchrollo14** [comment]
> @victorchrollo14 the feature looks like it works based on your recording. I wouldn't be surprised if you won't receive feedback to tweak the styles or for us todo so after merging.
> I would still like to test it and see how it performs and it might take a while until this is merged but I have a good feeling about this one, congratulations.

I just came up with a random implementation and was expecting someone would tell me to implement it in a better way or tweak it a bit.

I too am surprised that I was not asked to make changes in code. I'll fix it up if there are any issues.

**Review by avoinea — APPROVED** [review]
The Romanian translation looks good.

**Review by sneridagh — CHANGES_REQUESTED** [review]
@victorchrollo14 please look at the comment. BTW, very nice to the eye.

**Comment by victorchrollo14** [comment]
hey @sneridagh. does this look alright?

File: packages/volto/src/middleware/api.js [hunk 5]
```diff
@@ -188,7 +187,15 @@ const apiMiddlewareFactory =
...
                   },
                 ).then((reqres) => {
-                  dispatch(updateUploadedFiles(uploadedFiles++));
+                  if (item.op === 'post') {
+                    let uploadedFiles =
+                      getState().content.subrequests?.['batch-upload']
+                        ?.uploadedFiles;
+
+                    dispatch(
+                      updateUploadedFiles(++uploadedFiles, 'batch-upload'),
```
Comment (sneridagh) [inline packages/volto/src/middleware/api.js:196]: @victorchrollo14 the one getting the SUBREQUEST='batch-upload' is createContent action, when it's uploading files.

https://github.com/plone/volto/blob/8aa167a6d5ffb94f329dec42c0d9c96700ea27d6/packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx#L187-L204

Why the `updateUploadedFiles` needs it to be passed down at all?

Comment (victorchrollo14) [reply packages/volto/src/middleware/api.js:196]: > @victorchrollo14 the one getting the `SUBREQUEST='batch-upload'` is `createContent` action, when it's uploading files.
> 
> https://github.com/plone/volto/blob/8aa167a6d5ffb94f329dec42c0d9c96700ea27d6/packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx#L187-L204
> 
> Why the `updateUploadedFiles` needs it to be passed down at all?

createContent does not handle updating the uploadedFiles count, So I created updateUploadedFiles action that accepts `subrequest, uploadedFiles` properties and a  reducer that takes care of updating the uploadedFiles count  which I have added into subrequests['batch-upload'].
What do you think? should we use `createContent` itself for updating  the uploadedFiles count.

Comment (sneridagh) [reply packages/volto/src/middleware/api.js:196]: No no, the question is, why do you need to pass down the `subrequest` to `updateUploadedFiles`?

File: packages/volto/src/actions/content/content.js [hunk 6]
```diff
@@ -25,9 +25,10 @@ import config from '@plone/volto/registry';
  * @param {number} number of files uploaded
  * @returns {Object} update uploaded files action
  */
-export function updateUploadedFiles(uploadedFiles) {
+export function updateUploadedFiles(uploadedFiles, subrequest) {
   return {
     type: UPDATE_UPLOADED_FILES,
+    subrequest,
```
Comment (sneridagh) [inline packages/volto/src/actions/content/content.js:31]: Here, why?

File: packages/volto/src/reducers/content/content.js [hunk 7]
```diff
@@ -104,20 +103,36 @@ export default function content(state = initialState, action = {}) {
...
-            subrequests: {
-              ...state.subrequests,
-              [action.subrequest]: {
-                ...(state.subrequests[action.subrequest] || {
-                  data: null,
-                }),
-                loaded: false,
-                loading: true,
-                error: null,
+        ? action.subrequest === 'batch-upload'
```
Comment (sneridagh) [inline packages/volto/src/reducers/content/content.js:106]: Why did you have to add this?

File: packages/volto/src/middleware/api.js (hunk 5 above)
Comment (sneridagh) [inline packages/volto/src/middleware/api.js:196]: I was thinking more in something more simple like 

```js
if (action.subrequest === 'batched-upload') {
    dispatch(updateUploadedFiles(++uploadedFiles))
}
```
and that's it. Without anything that you did in the last commit. Is it possible?

File: packages/volto/src/actions/content/content.js (hunk 6 above)
Comment (victorchrollo14) [reply packages/volto/src/actions/content/content.js:31]: I thought I'll pass 'batch-upload' as a subrequest to `updateUploadedFiles` action, then the reducer would use it to update the `subrequests['batch-upload']` to something like this 
```
subrequests: {
'batch-upload': {
   data: null,
   error: null,
   loading: true,
   loaded: false,
   uploadedFiles: 1
}
```

File: packages/volto/src/middleware/api.js (hunk 5 above)
Comment (victorchrollo14) [reply packages/volto/src/middleware/api.js:196]: oh! that's what you meant.
Lol. I unnecessarily came up with something too complicated. 

I Tried out the above example. It works fine. 

[Screencast from 07-04-24 02:21:48 PM IST.webm](https://github.com/plone/volto/assets/89346667/7cd308e9-5e84-4907-9522-1d2ed248aff9)

**Comment by sneridagh** [comment]
@victorchrollo14 if it works well, please then simplify it and we are good to go.

**Comment by victorchrollo14** [comment]
> @victorchrollo14 if it works well, please then simplify it and we are good to go.

alright. I'll revert to the previous commit and push this change.

File: packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx [hunk 8]
```diff
@@ -388,7 +401,8 @@ export default compose(
   connect(
     (state) => ({
       request: state.content.subrequests?.[SUBREQUEST] || {},
+      uploadedFiles: state.content.uploadedFiles,
     }),
-    { createContent },
+    { createContent, updateUploadedFiles },
```
Comment (nileshgulia1) [inline packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx:406]: @victorchrollo14 Where are we dispatching this action in this file?

**Review by nileshgulia1 — COMMENTED** [review]
I like the UI part. Just left few questions and its good to go.

File: packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx (hunk 8 above)
Comment (victorchrollo14) [reply packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx:406]: Thanks for pointing it out, I initially imported it thinking I'll be using in content upload modal, but then I didn't use it there and forgot to remove it.

File: packages/volto/src/middleware/api.js [hunk 9]
```diff
@@ -133,6 +133,7 @@ const apiMiddlewareFactory =
     const { settings } = config;
 
     const token = getState().userSession.token;
+    let uploadedFiles = getState().content.uploadedFiles;
```
[the remark this answers is not in the document]
Comment (victorchrollo14) [reply packages/volto/src/middleware/api.js:136]: We could have created a new redux state for it. But then again it wouldn't make sense for a single property. So I added it to the contents state as Uploaded Files is related to it.

**Comment by sneridagh** [comment]
@plone/volto-team I need a final ack on this one, @nileshgulia1 are all your questions answered?

**Review by ichim-david — CHANGES_REQUESTED** [review]
@victorchrollo14 @plone/volto-team I don't like the way the the text is 
so janky as the counter increments and there is very poor contrast of the
text due to the gray overlay with the blue text.
I propose the following changes found in my gist
https://gist.github.com/ichim-david/0756e28aa1999d5d29ff7ebeede93413

And my changes would make the upload look and function as such.

https://github.com/plone/volto/assets/152852/59ef9812-ba0a-463b-be62-cb4c29025d66

If someone has a better solution of different color combination now's the time to speak or forever hold your tongue :)

EDIT:
In my video there is a small or close to small overlap when we have extra 0 such as 200. I've bumped up the width to 2.25 and now the issue is gone. Some of you guys might complain about having too much space to take into account the potential 3 digit file upload. 
Either someone comes up with a better css styling or maybe we need to pad the numbers with zeroes so if we have 50 it starts 01 if we upload 100+ it starts with 001 as a solution to avoid large spacing between the words and the incrementer.

**Comment by stevepiercy** [comment]
I dislike the spacing around the counter. I think it is OK to have the text jump as this happens in every progress bar I have ever watched, but if not, then I would left-align the text and replace it with two lines:

```
Files uploaded: <count>
Total files to upload: <total>
```

I agree that the contrast is too low between the counter text and its grey overlay background. However I think that a background color on the entire progress indicator container would be the better option. The rounded corners of both the counter text container and the progress bar stacked on top of each other is inconsistent with Pastanaga's principles of no rounded corners.

Finally, I think the progress bar itself should be rectangular without rounded corners.

**Comment by ichim-david** [comment]
> I dislike the spacing around the counter. I think it is OK to have the text jump as this happens in every progress bar I have ever watched, but if not, then I would left-align the text and replace it with two lines:
> 
> ```
> Files uploaded: <count>
> Total files to upload: <total>
> ```
> 
> I agree that the contrast is too low between the counter text and its grey overlay background. However I think that a background color on the entire progress indicator container would be the better option. The rounded corners of both the counter text container and the progress bar stacked on top of each other is inconsistent with Pastanaga's principles of no rounded corners.
> 
> Finally, I think the progress bar itself should be rectangular without rounded corners.

I like the 2 line solution and it would get rid of the spacing and counter padding needed and since it's the last text the previous text would probably remain in place.

I am fine with having a bg color for that section and getting rid of the rounded option if this is desired. 
@stevepiercy you might need to make a screenshot with your proposal so that we know exactly what you want for bg color

**Comment by stevepiercy** [comment]
> @stevepiercy you might need to make a screenshot with your proposal so that we know exactly what you want for bg color

As long as there is sufficient contrast, I'm OK with whatever is chosen. White appears to be the default background color, so I would go with that. However there might be an existing style or class that can be reused instead of creating a new one. `blocks-chooser` may be a good class to reuse.

**Comment by djay** [comment]
I'm not saying there is a need to change anything UI wise but quanta does have a design for how this should look.

If there are changes to the UI then it would be nice to make them in the direction of the quanta design?

image

Qunata doesn't say much about the progress bar works but we did an implementation of upload screen that worked with TUS that which means that it gives progress on individual files that are large. Not sure that can be done here as you might not get progress on progress on single files?

- image

The details for how we proposed the final upload UI would look are all in
#5423 

In any case, just a heads up this UI may change again in the future as the proposal was to switch to TUS for all uploads

**Comment by stevepiercy** [comment]
There are two other Quanta related PLIPs:

- https://github.com/plone/volto/issues/4332
- https://github.com/plone/volto/issues/4206

They are targeted for Plone 7 and depend on other parts that are beyond the scope of fixing this bug. I'd prefer to fix the bug now, reusing styles that already exist.

**Comment by ichim-david** [comment]
@stevepiercy @djay we have to take into consideration also the scope of this ticket which is to simply provide a progress bar with some info on how many files.

I took Steve's suggestion and tweaked the rounded corners of the progress and added the info on 2 lines.
I think this is a good solution but let's hear your opinion.

https://github.com/plone/volto/assets/152852/3df17c41-53a1-4ec0-879f-5786ca7d1c29

**Comment by stevepiercy** [comment]
@ichim-david the contrast is sufficient, and there's no more jumpy text. I think it is good. Would you please push a commit with your work?

I think we're waiting for input from @nileshgulia1.

**Comment by djay** [comment]
To be clear I wasn't referring to quanta styles but the layout and functionality.

**Review by nileshgulia1 — APPROVED** [review]

File: packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx [hunk 10]
```diff
@@ -40,6 +40,10 @@ const messages = defineMessages({
     defaultMessage:
       '{count, plural, one {Upload {count} file} other {Upload {count} files}}',
   },
+  uploadingFiles: {
+    id: 'Uploading {uploadedFiles} files out of {totalFiles}',
+    defaultMessage: 'Uploading {uploadedFiles} files out of {totalFiles}',
+  },
```
Comment (ichim-david) [inline packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx:46]:
```suggestion
   filesUploaded: {
    id: 'Files uploaded: ',
    defaultMessage: 'Files uploaded: ',
  },
  totalFilesToUpload: {
    id: 'Total files to upload: {totalFiles}',
    defaultMessage: 'Total files to upload: {totalFiles}',
  },
```

File: packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx [hunk 11]
```diff
@@ -234,13 +242,18 @@ class ContentsUploadModal extends Component {
...
-            </Loader>
+            <Progress
+              className="progress-bar"
+              value={this.props.uploadedFiles}
+              total={this.state.totalFiles}
+            >
+              {this.props.intl.formatMessage(messages.uploadingFiles, {
+                uploadedFiles: this.props.uploadedFiles,
+                totalFiles: this.state.totalFiles,
+              })}
```
Comment (ichim-david) [inline packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx:255]:
```suggestion
              {this.props.intl.formatMessage(messages.filesUploaded)}
              <span className="uploaded-files">{this.props.uploadedFiles}</span>
              <br />
              {this.props.intl.formatMessage(messages.totalFilesToUpload, {
                totalFiles: this.state.totalFiles,
              })}
```

**Review by ichim-david — CHANGES_REQUESTED** [review]
@victorchrollo14 I added as suggestions that you can batch and commit in a single commit the changes I suggest to the styling and the text content.
You will need to run pnpm y18n command to update the translations po files and use the latest translations messages.

File: packages/volto/locales/de/LC_MESSAGES/volto.po [hunk 12]
```diff
@@ -3978,16 +3978,16 @@ msgstr "Laden Sie ein Lead-Bild im Feld 'Lead-Bild' hoch."
 msgid "Upload files"
 msgstr "Datei hochladen"
```
Comment (ksuess) [inline packages/volto/locales/de/LC_MESSAGES/volto.po:3979]:
```suggestion
msgstr "Dateien hochladen"
```
Plural

**Review by ksuess — CHANGES_REQUESTED** [review]

**Comment by victorchrollo14** [comment]
> @stevepiercy @djay we have to take into consideration also the scope of this ticket which is to simply provide a progress bar with some info on how many files.
> 
> I took Steve's suggestion and tweaked the rounded corners of the progress and added the info on 2 lines. I think this is a good solution but let's hear your opinion.
> 
>  flex-two-lines.mp4

@ichim-david @stevepiercy @djay @sneridagh @nileshgulia1. Can we try something like this.
if this doesn't feel fine, then I'll make the changes @ichim-david suggested.

[Screencast from 01-05-24 03:10:15 PM IST.webm](https://github.com/plone/volto/assets/89346667/d61f09b7-4b10-4822-bd38-d620a7473e0d)

**Comment by stevepiercy** [comment]
@victorchrollo14 absolutely, positively, 100% YES! That is exactly what I imagined, but could not put into words. It looks consistent, accessible, and well-integrated.

**Comment by victorchrollo14** [comment]
> @victorchrollo14 absolutely, positively, 100% YES! That is exactly what I imagined, but could not put into words. It looks consistent, accessible, and well-integrated.

I'll push these changes then.

**Review by ichim-david — APPROVED** [review]
@victorchrollo14 I'm fine now with the changes, thank you for your work and the willingness to go through the necessary round of changes in order to make something even better than when it started as this is the strength of the open source community where you can receive feedback from several members and each can contribute to the successful outcome.

**Review by sneridagh — APPROVED** [review]
