### PR TITLE
Ensure hidden files get added to new addon projects in generator-volto

### LINKED ISSUE #5719: Some files starting with dot are not added in a new addon created with generator-volto
**Describe the bug**
Although the template has several files that start with a dot, such as [.dockerignore](https://github.com/plone/volto/blob/main/packages/generator-volto/generators/addon/templates/.dockerignore), [.editorconfig](https://github.com/plone/volto/blob/main/packages/generator-volto/generators/addon/templates/.editorconfig), etc., only [.gitignore](https://github.com/plone/volto/blob/main/packages/generator-volto/generators/addon/templates/.gitignorefile) is added.

**To Reproduce**

```
npm install -g @plone/generator-volto
yo @plone/volto test-volto
cd test-volto
yo @plone/volto:addon myaddon
```

**Expected behavior**
All files that start with dot in the template must be in the generated addon

**Software (please complete the following information):**

- OS: Ubuntu 22
- Volto Version : 17.11.5

**Additional context**
It looks like [.gitignore] was added after @instification 's PR: https://github.com/plone/volto/pull/5258

### PR DESCRIPTION
**Pull request by instification**
Fixes #5719 

The fix for #5258 prevented dotfiles from being copied over. This adds a new copy to ensure all hidden files get copied too.

### CODE REVIEW

File: packages/generator-volto/generators/addon/index.js [hunk 1]
```diff
@@ -206,24 +206,22 @@ Run "npm install -g @plone/generator-volto" to update.`,
...
+    this.fs.copyTpl(this.templatePath('**/.*'), this.destinationPath(), {
+      ignore: ['**/*.tpl', '**/*~', '**/.gitignorefile'],
+    });
+
+    // Copy .gitignorefile to .gitignore
     this.fs.copyTpl(
       this.templatePath('.gitignorefile'),
       this.destinationPath('.gitignore'),
       this.globals,
     );
```
Comment (wesleybl) [inline packages/generator-volto/generators/addon/index.js:218]: `.gitignorefile` is not a template. Then a simple copy of it can be made.

**Review by wesleybl — CHANGES_REQUESTED** [review]

**Comment by wesleybl** [comment]
It would be nice to add the hidden files in the test:

https://github.com/plone/volto/blob/aa53b68e46e6caec2b6ca028ecdda91395a3e88d/packages/generator-volto/__tests__/test_addon.js#L10

File: packages/generator-volto/generators/addon/index.js (hunk 1 above)
Comment (instification) [reply packages/generator-volto/generators/addon/index.js:218]: I don't mind changing it but I don't think it does any harm as a template? If somebody later wanted to add template syntax to the file then it would just work without needing to modify this code.

**Comment by instification** [comment]
@wesleybl thanks for your comments. If I get some time I'll try and move this forward to review. I'd like to spend a bit more time exploring my previous PR and maybe reverting that and fixing the issue it was solving in a way that doesn't break copying hidden files.

Please feel free to push any changes you think are needed to this branch yourself.

**Comment by sneridagh** [comment]
@instification @wesleybl I just realised by myself of the severity of this... My bad not having understood this one correctly and I left it to rot in here, but please raise hand and use common sense on the severity of the problems, specially this ones that are so easy to slip away. It's very important that our first time experience of someone using Volto is exquisite. Also, the ones already using it we should look after that these things get fixed.

Please ping me more vehemently next time.
